#pragma once

#include "Singleton.h"
#include "Renderable.h"
#include "Controllable.h"
#include "Updateable.h"
#include "Vector.h"
#include "Common.h"
#include "Timer.h"
#include "Sprite.h"

#include <string>
#include <queue>
#include <variant>
#include <memory>


namespace Zelda
{

// RGB components of text colour
constexpr int TEXT_R = 248;
constexpr int TEXT_G = 248;
constexpr int TEXT_B = 168;

// Texture dimensions
constexpr int DIALOGUE_WIDTH = 144;
constexpr int DIALOGUE_HEIGHT = 40;

// Position of textbox on screen
constexpr int DIALOGUE_POS_X = 8;
constexpr int DIALOGUE_POS_Y_LOW = 80;
constexpr int DIALOGUE_POS_Y_HIGH = 8;

// Position of text in textbox
constexpr int TEXT_POS_X = 8;
constexpr int TEXT_POS_Y = 8;

// Red arrow more text indicator position
constexpr int ARROW_POS_X = 135;
constexpr int ARROW_POS_Y = 32;

// Max characters per line
constexpr int MAX_CHAR_PER_LINE = 16;
constexpr int LINE_HEIGHT = 16;
constexpr int MAX_LINES = 2;

// Dimensions of a character
constexpr int CHAR_WIDTH = 8;
constexpr int CHAR_HEIGHT = 8;

constexpr float TEXT_SPEED = 1 / 45.0f;
constexpr int SCROLL_SPEED = 4;

constexpr float SELECTOR_FPS = (1.0f / 4.0f);

class Dialogue : public Renderable, public Controllable, public Singleton<Dialogue>, public Updateable
{
    friend class Singleton<Dialogue>;
public:

    void message(const std::string& message, float yPos) noexcept;
    bool question(const std::string& question, const std::string& choice1, const std::string& choice2, float yPos) noexcept;
    
    void render() noexcept override;
    void update() noexcept override;
    void control() noexcept override;
private:
    Dialogue();

    // Position of textbox
    int m_dialoguePosX;
    int m_dialoguePosY;

    Timer m_textTimer;
    std::string m_choice;
    std::string m_choice1;
    std::string m_choice2;

    std::string m_message;
    int m_currentChar;
    int m_currentLine;
    int m_dstCharX;
    int m_dstCharY;
    std::shared_ptr<Sprite> m_text;
    std::unique_ptr<Sprite> m_subTexture;
    bool m_moreText;

    bool m_flashQuestion;
    Timer m_questionTimer;
    int m_questionXPos;
    int m_questionYPos;
    bool m_isQuestion;
    std::shared_ptr<Sprite> m_questionMarker;

    // Continue arrow
    Timer m_redArrowTimer;
    bool m_flashArrow;
    std::shared_ptr<Sprite> m_redArrow;
    bool m_continue;
    bool m_scrollMessage;
    int m_scrolledLines;
    Timer m_scrollTimer;

    struct Message
    {
        std::string message;
        float yPos;
        Message(const std::string& message, const float yPos) : message(message), yPos(yPos) {}
    };

    struct Question
    {
        std::string question;
        float yPos;
        int questionXPos;
        int questionYPos;
        std::string choice1;
        std::string choice2;
        Question(const std::string& question, const float yPos, const int questionXPos, const int questionYPos,
            const std::string& choice1, const std::string& choice2) : question(question),
            yPos(yPos), questionXPos(questionXPos), questionYPos(questionYPos), choice1(choice1), choice2(choice2) {}
    };

    using MessageQuestion = std::variant<Message, Question>;
    
    // Queue messages
    std::queue<MessageQuestion> m_messageQueue;

    void reset() noexcept;
    void checkCharacters(const std::string& string) const noexcept;

    // All the dialogue from the game
    // Credits go to https://github.com/zladx/LADX-Disassembly for providing the text

    // TODO: Remove duplicate lines from here
    /*
    const std::string m_dialogue[159 + 89 + 135 + 184 + 98 + 4] =
    {
        "Whoa, boy! Where""ya off to in    ""such a hurry?   ""Set a spell, I  ""got somethin' ta""tell ya!@",
        "What a relief! I""thought you'd   ""never wake up!  ""You were tossing""and turning...  ""What?  Zelda?   ""No, my name's   ""Marin!  You must""still be feeling""a little woozy. ""You are on      ""Koholint Island!@",
        "Follow the lane ""south to reach  ""the beach where ""I found you.    ""Since you washed""ashore, lots of ""nasty monsters  ""have been in the""area, so be     ""careful, okay?@",
        "Hi!  Tarin went ""to the forest to""look for toad-  ""stools, but I'd ""rather sing.    ""Listen to this, ""it's called the ""'Ballad of the  ""Wind Fish.'@",
        "Hey!  That's a  ""nice Ocarina you""have there! Will""you accompany   ""me as I sing?@",
        "I just love to  ""sing-- what can ""I say?  What do ""you like to do, ""#####?@",
        "#####, Tarin's  ""taking a nap at ""home.  I don't  ""know how he can ""sleep on such a ""nice day!  It   ""makes me want to""sing a song...  ""Yes, the song is""'Ballad of the  ""Wind Fish!'@",
        "Eh? It's locked!""You can open the""door with the   ""Nightmare Key.@",
        "You got a Piece ""of Power!  You  ""can feel the    ""energy flowing  ""through you!@",
        "Ahhh... It has  ""the Sleepy Toad-""stool, it does! ""We'll mix it up ""something in a  ""jiffy, we will!@",
        "The last thing I""kin remember was""bitin' into a   ""big juicy toad- ""stool... Then, I""had the darndest""dream... I was a""raccoon!  Yeah, ""sounds strange, ""but it sure was ""fun!@",
        "I'm all tucker'd""out...  I think ""I better set a  ""spell before I  ""head home...@",
        "Double double,  ""toil and trouble""a toadstool mix ""makes powder for""tricks!@",
        "As a raccoon, my""nose is verrry  ""sensitive, ta   ""stuff like dust ""and powder...@",
        "It's the toad-  ""stool you picked""in the woods.   ""What is it for? ""You hold it over""your head and a ""mellow aroma    ""wafts into your ""nostrils.@",
        "You pick the    ""toadstool... As ""you hold it over""your head, a    ""mellow aroma    ""flows into your ""nostrils.@",
        "Hrrrm...Snore...""Hunh?... If'n ya""don' know...call""old man Ulrira! ""Zonk...Snore...@",
        "I'm tired... I'm""goin' ta sleep  ""now... Zzzzzz...@",
        "Well that was a ""surprise!  Hey! ""I'll tell you a ""secret! Use your""sword to poke at""dungeon walls...""If you hear a   ""hollow clank,   ""you can break   ""the wall with a ""Bomb!@",
        "You've learned  ""the 'Ballad of  ""the Wind Fish!' ""This song will  ""always remain in""your heart!@",
        "Please remember ""this song!  You ""should play it  ""every once in a ""while to keep it""fresh in your   ""mind!@",
        "Please!  I want ""you to learn it!""This song is my ""favorite!@",
        "So, how do you  ""like it?  It's  ""really touching,""isn't it?  Does ""it stick in your""mind?           ""    Yes  No<ask>",
        "Hi there, big   ""guy!  I'm Crazy ""Tracy!  I've got""a little secret ""for sale that'll""pump you up!@",
        "Will you give me""28 Rupees for my""secret?         ""    Give Don't<ask>",
        "How about it?   ""42 Rupees for my""little secret...""    Give Don't<ask>",
        "All right, come ""here and I'll   ""rub it on you!  ""...There... I've""applied my own  ""secret medicine!""It will take    ""effect when you ""lose all heart! ""Drop by again,  ""big guy!@",
        "Beat it, then!  ""Come back when  ""you have some   ""cash!@",
        "... ... ... ... ""But I won't sell""it to you!@",
        "Well!  I'm only ""offering you a  ""secret that will""make you strong!""You're such a   ""chicken!!@",
        "...You're so    ""cute!  I'll give""you a 7 Rupee   ""discount!@",
        "You got Marin!  ""Is this your big""chance?@",
        "GRRRR...@",
        "Heh heh heh ho! ""You're goin' ta ""be lost, thanks ""to me!  Heh heh!@",
        "BOW WOW!        ""BOW WOW!@",
        "YIP YIP!        ""YIP YIP!@",
        "Let's heal your ""wounds and get  ""rid of all that ""stress... Close ""your eyes and   ""relax...@",
        "You dirty rat!  ""You k-k-k...beat""my brothers!    ""You'll pay!!    ""I'll never      ""forget you!@",
        "Hey runt!  You  ""think you can   ""take me?!  All  ""right boys, get ""this punk out   ""of my face!@",
        "Yep!  Those're  ""my boys!  I'm   ""Papahl, pleased ""ta meetcha! I'll""be lost in the  ""hills later, so ""keep a look out ""for me, hear?@",
        "Yes!!  Yes!!    ""Break them!     ""Break them all! ""... ... ... ... ""What?  What's   ""wrong?@",
        "Aye Caramba!    ""Kid, you have a ""lot to learn,   ""trying to buy   ""something you   ""have no use for!@",
        "You've got a    ""Heart!  Thump!  ""One of your     ""Heart Containers""is filled!@",
        "Bow & Arrow Set ""Only 980 Rupees!""    Buy  No Way<ask>",
        "   10 Arrows    ""   10 Rupees    ""    Buy  Don't<ask>",
        "Hey!  Welcome!  ""See something   ""you like?!  Just""bring it here!@",
        "Hey! You! Stop! ""You gotta pay!  ""Put it back!@",
        "  Deluxe Shovel ""   200 Rupees!  ""Seems expensive!""    Buy  No Way!""<ask>",
        "   Three Hearts ""    10 Rupees!  ""    Buy  Don't<ask>",
        "     Shield     ""    20 Rupees!  ""    Buy  Don't<ask>",
        "    Ten Bombs   ""    10 Rupees   ""    Buy  Don't<ask>",
        "Sorry, kid!  You""don't have the  ""Rupees!  Come   ""back when you   ""have the cash!@",
        "Thanks a lot!   ""And come again!@",
        "Guess what?  You""got it for free.""Are you proud of""yourself?@",
        "I wasn't kidding""when I said pay!""Now, you'll pay ""the ultimate    ""price!!@",
        "Hunh?  It sounds""like the castle ""gate opened! You""can easily leave""the castle now!@",
        "  TRENDY GAME!  "" One Play 10 Rs.""    Play No<ask>",
        "The A and B     ""Buttons move the""crane...The rest""is just timing! ""Go over to the  ""buttons to play!""Good Luck!@",
        "It's a Shield!  ""There is space  ""for your name!@",
        "Challenge Again?""    Play No<ask>",
        "Good Luck!@",
        "We're closing up""for today!  Come""again, anytime!@",
        "You got some    ""Magic Powder!   ""Try to sprinkle ""it on many      ""things!@",
        "It's 30 Rupees! ""You can play the""game three more ""times with this!@",
        "Cough Cough...  ""Don't sprinkle  ""that on me...   ""...I'll have to ""curse you!      ""Cough Cough...@",
        "You got a Yoshi ""Doll!  Recently,""he seems to be  ""showing up in   ""many games!@",
        "How about some  ""fishing, little ""buddy? I'll only""charge you 10   ""Rupees...       ""    Fish Not Now""<ask>",
        "You have to have""more passion!   ""Live a little!@",
        "Okay, here's how""you do it.  Use ""<left> and <right> on the <dpad>""to aim a cast.  ""Once you hook a ""fish, press the ""Button rapidly  ""to reel him in!@",
        "Why not try one ""more time,      ""little buddy?   ""    Cast Not Now""<ask>",
        "Wow! That one   ""got away!  Want ""to try again?   ""    Cast Not Now""<ask>",
        "Wow! Nice Fish! ""It's a lunker!! ""I'll give you a ""20 Rupee prize! ""Try again?      ""    Cast Not Now""<ask>",
        "This pond's all ""fished out.  Why""not try your    ""luck in the sea?""    Okay No<ask>",
        "Did I say that? ""Forget it, okay?""Run along now...@",
        "It's a runt!    ""I'll only give  ""you a 5 Rupees  ""prize for that. ""You should try  ""again!          ""    Okay No<ask>",
        "You're short of ""Rupees?  Don't  ""worry about it. ""You just come   ""back when you   ""have more money,""little buddy.@",
        "You've got a    ""Piece of Heart! ""Press SELECT on ""the Subscreen   ""to see.@",
        "You collected   ""four Pieces of  ""Heart.  Now, you""have a complete ""Heart Container!@",
        "Brrrr... This is""a block of solid""ice!  It's very ""cold!@",
        "NYAH NYAH! You  ""can't hurt me as""long as I have  ""my bottle!@",
        "Waaaah! You- you""broke my bottle!""Why, you... You ""make me hopping ""mad!!!@",
        "Well, #####, ya ""finally snapped ""out of it...    ""Name's Tarin... ""Hope yer feelin'""better...  What?""How did I know  ""your name?  You ""think it's weird""eh?  Well, I saw""it on back of   ""this shield!@",
        "Oh, yeah... Some""other stuff like""this washed up  ""on the beach... ""If'n you go look""watch out for   ""monsters! Ever  ""since you showed""up, #####, I've ""seen 'em all    ""over the place!@",
        "Level 1--       ""     Tail Cave@",
        "Level 2--       ""   Bottle Grotto@",
        "Level 3--       ""      Key Cavern@",
        "Level 4--       "" Angler's Tunnel@",
        "Level 5--       ""   Catfish's Maw@",
        "Level 6--       ""     Face Shrine@",
        "Level 7--       ""   Eagle's Tower@",
        "Level 8--       ""     Turtle Rock@",
        "Wind Fish's Egg @",
        "Mountain Bridge @",
        "Sale's House O' ""    Bananas@",
        "Pothole Field@",
        "    House By    ""     The Bay@",
        "   Trendy Game@",
        "  Town Tool Shop@",
        "Marin and       ""   Tarin's House@",
        "   Witch's Hut@",
        "  Yarna Desert@",
        "  Ukuku Prairie@",
        "Mysterious Woods@",
        "  Mt. Tamaranch @",
        "     Tal Tal    "" Mountain Range @",
        "  Signpost Maze @",
        "  Mabe Village  @",
        " Animal Village @",
        "    Cemetery    @",
        "   Rapids Ride  @",
        "Koholint Prairie@",
        " Toronbo Shores@",
        "  Martha's Bay@",
        "East of the Bay@",
        "  Goponga Swamp@",
        "   Face Shrine @",
        " Kanalet Castle@",
        "Tal Tal Heights@",
        "Tabahl Wasteland@",
        "  South of the  ""    Village@",
        "  Fishing Pond  @",
        "Madam MeowMeow's""     House      "" Beware of Dog!@",
        "Old Man Ulrira's""     House      @",
        "Weird Mr. Write @",
        " Crazy Tracy's  ""  Health Spa@",
        "Quadruplet's    ""      House@",
        "  Dream Shrine  @",
        "Telephone Booth ""<down> Signpost Maze @",
        "Seashell Mansion@",
        "Richard's Villa @",
        "     Hen House  @",
        "Village Library @",
        "    Raft Shop   @",
        "    Warp Hole   @",
        "This rock has   ""many cracks...  ""There must be   ""some way to     ""shatter it...@",
        "Oh? What a weird""object!  There  ""must be some way""to tackle this  ""obstacle.@",
        "Hunh?  This rock""has a key hole! ""You should come ""back with a key!@",
        "Wow!  This looks""pretty heavy!   ""You won't be    ""able to lift it ""with just your  ""bare hands...@",
        "Well, it's an   ""Ocarina, but you""don't know how  ""to play it...@",
        "No!  No!  Poor  ""hen!  Stop that!@",
        "You found the   ""Power Bracelet! ""At last, you can""pick up pots and""stones!@",
        "You got your    ""shield back!    ""Press the button""and repel       ""enemies with it!@",
        "Ahhh... Yess... ""That dust was so""refreshing...   ""For that, I'll  ""tell you a hint!""Use a Bomb in a ""place where the ""sand swallows   ""you... There is ""a treat on the  ""other side of   ""the wall... Bye!@",
        "You've got the  ""Hook Shot!  Its ""chain stretches ""long when you   ""use it!@",
        "You've got the  ""Magic Rod!  Now ""you can burn    ""things! Burn it!""Burn, baby burn!@",
        "You've got the  ""Pegasus Boots!  ""If you hold down""the Button, you ""can dash!@",
        "You've got the  ""Ocarina!  You   ""should learn to ""play many songs!@",
        "You've got the  ""Roc's Feather!  ""It feels like   ""your body is a  ""lot lighter!@",
        "You've got a    ""Shovel!  Now you""can feel the joy""of digging!@",
        "You've got some ""Magic Powder!   ""Try sprinkling  ""it on a variety ""of things!@",
        "You've got a    ""bomb! Way to    ""go!@",
        "You found your  ""Sword!  It must ""be yours because""it has your name""engraved on it!@",
        "You've got the  ""Flippers! If you""press the B     ""Button while you""swim, you can   ""dive underwater!@",
        "You've got the  ""Magnifying Lens!""This will reveal""many things you ""couldn't see    ""before!@",
        "You've got a    ""new Sword!  You ""should put your ""name on it right""away!@",
        "You found the   ""secret medicine!""You should apply""this and see    ""what happens!@",
        "You've got the  ""Tail Key!  Now  ""you can open the""Tail Cave gate!@",
        "You've got the  ""Slime Key!  Now ""you can open the""gate in Ukuku   ""Prairie!@",
        "You've got the  ""Angler Key!@",

        "You've got the  ""Face Key!@",
        "You've got the  ""Bird Key!@",
        "At last, you got""a Map!  Press   ""the START Button""to look at it!@",
        "You've got the  ""Compass!  Now,  ""you can see     ""where the chests""and Nightmare   ""are hidden! This""Compass has a   ""new feature-- a ""tone will tell  ""you if a key is ""hidden in a room""when you enter! @",
        "You found a     ""stone beak!     ""Let's find the  ""owl statue that ""belongs to it.@",
        "You've got the  ""Nightmare's Key!""Now you can open""the door to the ""Nightmare's     ""Lair!@",
        "You got a Small ""Key!  You can   ""open a locked   ""door.@",
        "   You got 20   ""     Rupees!    ""      JOY!@",
        "    You got 50  ""      Rupees!   ""    Very Nice!@",
        "   You got 100  ""     Rupees!    ""  You're Happy!@",
        "   You got 200  ""     Rupees!    ""You're Ecstatic!@",
        "Leave me alone! ""I'm trying to   ""sit still so    ""Schule can paint""my portrait!@",
        "BUZZZZZ! BUZZZZ!""   OUTZZZIDER!  @",
        "NEENER NEENER!  ""You can't find  ""me!  NYAH NYAH!@",
        "BLOOOP! BLOOOP! ""  GLUB!  GLUB!  ""OGGGH!  FOOOOD! ""BLOOOOP!  GLUB!@",
        "Ssso...you are  ""the outsssider, ""come to wake the""Wind Fisssh...  ""KEEE-HEE-HEEEH! ""I shall eat you!@",
        "HO HO HO!       ""I'm your bad guy""this time!!     ""HO HO HO!@",
        "TSSSK, TSSSK!   ""You don't ssseem""to know what    ""kind of island  ""thisss iss...   ""KEEE-HEEE-HEEE! ""What a fool...  ""KEE-HEE-HEH!!@",
        "Hey dummy! Need ""a hint?  My weak""point is... !!  ""Whoops!  There I""go, talking too ""much again...@",
        "Okay, listen up!""If the Wind Fish""wakes up, every-""thing on this   ""island will be  ""gone forever!   ""And I do mean...""EVERYTHING!@",
        "My energy...    ""gone...I...lost!""But you will be ""lost too, if the""Wind Fish wakes!""Same as me...you""...are...in...  ""his...dream...@",
        "BAH!  I'm not   ""going to hold   ""back!  I'm going""to make you wish""you were never  ""born!!@",
        "CRACKLE-FWOOOSH!""You're finished!""I will never let""you play the    ""Instruments of  ""the Sirens!!@",
        "C-C-CRACKLE!    ""Why did you come""here?  If it    ""weren't for you,""nothing would   ""have to change! ""You cannot wake ""the Wind Fish!  ""Remember, you...""too...are in... ""...the dream...@",
        "Hoot!  Ho, brave""lad, on your    ""quest to wake   ""the dreamer!    ""Welcome to the  ""Mysterious Wood!""Much of mystery ""you will find on""this uncharted  ""Koholint island!""I'm afraid you  ""may find it a   ""trifle difficult""to leave the    ""island while the""Wind Fish naps. ""...By the by,   ""have you ever   ""visited the Tail""Cave, which is  ""south of the    ""village?  Go    ""there with the  ""key you find in ""this forest...  ""The Wind Fish is""watching...Hoot!@",
        "Hoot!  Take the ""key and go to   ""the Tail Cave.  ""Retrieve the    ""Instrument that ""is hidden there!""Go now!  The    ""Wind Fish is    ""waiting!  Hooot!@",
        "Hoooot!  That is""an 'Instrument  ""of the Sirens!' ""I have to admit,""at first I did  ""not believe you ""were real...    ""That Instrument,""along with the  ""seven others in ""the set, has the""power to wake   ""the Wind Fish!  ""You must collect""them all!  I was""instructed to   ""give you direc- ""tions...  Your  ""next goal is    ""north, in       ""Goponga Swamp!! ""Hoot, indeed!@",
        "Hoot!  That is a""fearsome looking""animal you have ""there!  Do not  ""forget, the next""Instrument is in""Goponga Swamp!@",
        "Hoooot! The Wind""Fish sleeps long""and dreamily in ""the Egg above...""When you play   ""the eight Siren ""Instruments in  ""front of the Egg""he will awaken. ""This, my friend,""is the only way ""for you to leave""the island! Hoo!@",
        "Hoot!  How many ""Instruments     ""have you gotten ""so far?  When   ""you play the    ""Instruments in  ""front of the    ""Egg, the Wind   ""Fish will wake  ""and you will    ""leave this      ""island.  Now,   ""you must hasten ""to the Yarna    ""Desert!  The    ""dark, monstrous ""inhabitants of  ""the sand will   ""show you the    ""way! Hoot Hoot!@",
        "Hoot!  The shape""of the key shows""a fish, swimming""up a cascade of ""water!  Go now  ""to the mountain ""waterfall!  A   ""leap from the   ""top and you will""reach your goal!@",
        "Hoot!  There are""two shrines, one""to the north,   ""the other to the""south.  First,  ""head south,     ""where ancient   ""ruins speak of  ""the Wind Fish...""You will learn  ""much there...@",
        "Hoot!  I see you""have read the   ""relief...  While""it does say the ""island is but a ""dream of the    ""Wind Fish, no   ""one is really   ""sure...  Just as""you cannot know ""if a chest holds""treasure until  ""you open it, so ""you cannot tell ""if this is a    ""dream until you ""awaken...  The  ""only one who    ""knows for sure  ""is the Wind     ""Fish...  Trust  ""your feelings...""Someday you will""know for sure...@",
        "Hoot!  The many ""monsters of this""island fear that""the Wind Fish is""about to awaken!""The monsters'   ""power is real!  ""They may conquer""the island and  ""destroy their   ""foes!  That day ""may come soon!  ""Now, go to the  ""mountain tower! ""Fly like a bird!""Hoot! Hoot!@",
        "Hoot hoot!      ""Your path is    ""not easy, but   ""you are almost  ""there. Go east. ""The Wind Fish   ""is getting      "" restless.@",
        "Hoot!  It has   ""been some time  ""since our paths ""crossed, lad.   ""You must dive   ""into the waters ""of Martha's Bay ""to enter the    ""Catfish's Maw...""The closer you  ""get to the Wind ""Fish, the more  ""restless he     ""sleeps.  Carry  ""onward!  Hoot!@",
        "Hoot!  That girl""sang her song in""front of the    ""Egg! Her 'Ballad""of the Wind     ""Fish' is a song ""of awakening!   ""Did she actually""intend to wake  ""the Wind Fish?! ""The next Sirens'""Instrument is in""the west.  Play ""your melodies so""the unliving    ""stones might    ""hear!  Show your""courage!  The   ""Wind Fish waits ""for you!  Hoot!@",
        "The time has    ""come... The Wind""Fish awaits...  ""Enter the Egg...""Hoot! Hoot!@",
        "Hoot! Young lad,""I mean... #####,""the hero!  You  ""have defeated   ""the Nightmares! ""You have proven ""your wisdom,    ""courage and     ""power!          ""... ... ... ... ""As part of the  ""Wind Fish's     ""spirit, I am the""guardian of his ""dream world...  ""But one day, the""Nightmares      ""entered the     ""dream and began ""wreaking havoc. ""Then you, #####,""came to rescue  ""the island...   ""I have always   ""trusted in your ""courage to turn ""back the Night- ""mares.  Thank   ""you, #####... My""work is done... ""The Wind Fish   ""will wake soon. ""Good bye...Hoot!@",
        "... ... ... ... "" ... ... ... ..."" I AM THE WIND  ""      FISH...   "" LONG HAS BEEN  ""  MY SLUMBER... "" IN MY DREAMS..."" AN EGG APPEARED""     AND WAS    ""SURROUNDED BY AN""  ISLAND, WITH  ""PEOPLE, ANIMALS,""AN ENTIRE WORLD!""... ... ... ... ""  BUT, VERILY,  ""IT BE THE NATURE""  OF DREAMS TO  ""END! WHEN I DOST""AWAKEN, KOHOLINT"" WILL BE GONE...""ONLY THE MEMORY "" OF THIS DREAM  ""LAND WILL EXIST ""  IN THE WAKING ""      WORLD...  "" SOMEDAY, THOU  ""MAY RECALL THIS "" ISLAND...  THAT"" MEMORY MUST BE "" THE REAL DREAM ""     WORLD...   ""... ... ... ... "" COME, #####... ""LET US AWAKEN...""   TOGETHER!!@",
        " PLAY THE EIGHT ""  INSTRUMENTS!  ""PLAY THE SONG OF""   AWAKENING!!@",
        "Mermaid Statue  @",
        "...#####, you   ""have beaten all ""the Nightmares! ""Climb the stairs""before you!@",
        "Ach! Vat are you""looking at vith ""zat magnifying  ""lens?  Stop it  ""at vonce!@",
        "  Hoot!  Hoot!  ""So you are the  ""lad who owns the""sword...  Now I ""understand why  ""the monsters are""starting to act ""so violently... ""A courageous lad""has come to wake""the Wind Fish...""It is said that ""you cannot leave""the island      ""unless you wake ""the Wind Fish...""You should now  ""go north, to the""Mysterious      ""Forest.  I will ""wait for you    ""there!  Hoot!@",
        "Annoyance!  You ""are only getting""in the way!@",
        "Ribbit!  Ribbit!""Hey, man, I'm   ""Mamu, on vocals!""Brother, you    ""look like you   ""don't know      ""squat about     ""music!  Ribbit!@",
        "Ribbit!  Ribbit!""I'm Mamu, on    ""vocals!  But I  ""don't need to   ""tell you that,  ""do I?  Everybody""knows me!  Want ""to hang out and ""listen to us    ""jam?  For 300   ""Rupees, we'll   ""let you listen  ""to a previously ""unreleased cut! ""What do you do? ""    Pay  Leave<ask>",
        "Thank you...    ""Thank you very  ""much... Croak!@",
        "Well, that's a  ""shame, but we   ""don't play for  ""free!@",
        "You've learned  ""The Frog's Song ""of Soul!  It's a""very moving     ""tune... It can  ""even liven up   ""unliving things!@",
        "If you play this""song, you'll    ""make everything ""around you feel ""more alive!@",
        "Hey, Kid!  You  ""woke me up from ""a fine nap!!    ""...Thanks a lot!""But now, I'll   ""get my revenge! ""Are you ready?! ""    Yes  N-No<ask>",
        "I'll let you    ""carry more Magic""Powder!  He He! ""Are you ready?! ""    Yes  N-No<ask>",
        "Okay, I'll let  ""you carry more  ""Bombs! He He He!""Are you ready?! ""    Yes  N-No<ask>",
        "Fine, I'll let  ""you have more   ""arrows! Heh Heh!""Are you ready?! ""    Yes  N-No<ask>",
        "Heh Heh Heh!    ""You deserve it! ""Now look at all ""that junk you   ""have to carry!  ""Hah!  Take care!""See you again!@",
        "??  There is a  ""picture carved  ""on the wall, but""you can't see it""because it's too""dark in here...@",
        "TO THE FINDER...""  THE ISLE OF   ""KOHOLINT, IS BUT""  AN ILLUSION..."" HUMAN, MONSTER,"" SEA, SKY... A  ""SCENE ON THE LID"" OF A SLEEPER'S ""  EYE...  AWAKE ""THE DREAMER, AND""  KOHOLINT WILL ""VANISH MUCH LIKE""  A BUBBLE ON A ""NEEDLE... CAST- ""AWAY, YOU SHOULD""KNOW THE TRUTH! ""... ... ... ... ""What?  Illusion?@",
        "You've found a  ""Gold Leaf! Press""START to see    ""how many you've ""collected!@",
        "At last!  You've""got the final   ""Golden Leaf!    ""Now go and see  ""Richard about   ""that key...@",
        "You've got a    ""Guardian Acorn! ""It will reduce  ""the damage you  ""take by half!@",
        "You've got the  ""Mirror Shield!  ""You can now turn""back the beams  ""you couldn't    ""block before!@",
        "You've got a    ""more Powerful   ""Bracelet!  Now  ""you can almost  ""lift a whale!@",
        "You found a     ""Secret Seashell!""If you collect a""lot of these,   ""something good  ""is bound to     ""happen!@",
        "Want to go on a ""raft ride for a ""hundred Rupees? ""    Yes  No Way<ask>",
        "Okay, the raft  ""is ready for you""outside!  Enjoy!@",
        "Waterfall at the""    Shrine@",
        " South of the   ""    Shrine@",
        "Entrance to the "" Animal Village@",
        "We were born of ""nightmares... To""take over this  ""world, we made  ""the Wind Fish   ""sleep endlessly!""If the Wind Fish""doesn't wake up,""this island will""never disappear!""We would have   ""been the masters""of this place...""But you had to  ""come here and   ""disrupt our     ""plans!  Heh heh!""You can never   ""defeat us!!!    ""Let's rumble!@",
        "This island is  ""going to dis-   ""appear...  Our  ""world is going  ""to disappear... ""Our world...    ""Our... world... @",
        "Wow!  #####, can""I try this?!    ""What do you say?""    Okay No Way<ask>",
        "C'mon!  I want  ""to do it! Can I?""It looks so fun!""    Yes  Okay<ask>",
        "You're good!    ""You're a pro,   ""aren't you?     ""... ... ... ... ""Well, beat it!  ""Pros aren't     ""allowed in here!@",
        "Go away!@",
        "Quit it!@",
        "This is not a   ""chest...  What? ""You knew that?  ""Okay.@",
        "##### checked   ""the chest.  Wow!""This is a nice  ""chest!@",
        "It's all ready, ""it is!  Take    ""care, as there's""not much there! ""Why not try a   ""bit in my hut?@",
        "Hey!  What are  ""ya doin' in my  ""chest?!  Where'd""you learn ta do ""such a thing?!@",
        "You've got the  ""Full Moon Cello!@",
        "You've got the  ""Conch Horn!@",
        "You've got the  ""Sea Lily's Bell!@",
        "You've got the  ""Surf Harp!@",
        "You've got the  ""Wind Marimba!@",
        "You've got the  ""Coral Triangle!@",
        "You've got the  ""Organ of        ""  Evening Calm!@",
        "You've got the  ""Thunder Drum!@",

        "Hi! It's me, the""photographer!   ""You seem curious""about Grandpa   ""Ulrira.@",
        "I'll call this  ""'##### Dis-     ""covers Ulrira's ""Secret!'@",
        "#####, now run  ""away before he  ""finds you.@",
        "I'll go develop ""this. Come see  ""it later, OK?@",
        "I just LOVE to  ""take pictures.  ""Will you let me ""take your       ""picture?        ""    YES  NO<ask>",
        "Go to the back  ""of the room and ""stand in front  ""of the screen.@",
        "Hey! I haven't  ""taken your      ""picture yet! Go ""back and stand  ""in front of the ""screen!@",
        "I'll call this  ""'Here Stands A  ""Brave Man.'     ""Say cheese!@",
        "This owl statue ""is trying to say""something, but  ""you can't       ""understand it   ""because it has  ""no beak.@",
        "'I've got what  ""was inside this ""box.  Come and  ""get it, if you  ""can!'  Master <skull>@",
        "Gulp!  You found""me!  You're a   ""real pesky kid, ""you know that?!@",
        "Arrgh!  I can't ""beat you!  I'm  ""outta here!@",
        "You again?!  You""keep going and  ""going... I can't""outlast you!    ""All right, let's""do it!@",
        "WOOF! Dig! RUFF!@",
        "You put the     ""missing scale in""the mermaid     ""statue!@",
        "Hey! Be more    ""careful next    ""time!@",
        "Hey, man!  When ""you want to save""just push all   ""the Buttons at  ""once!  Uhh...   ""Don't ask me    ""what that means,""I'm just a kid!@",
        "Well, it seems  ""that after you  ""save, you will  ""start at the    ""last door you   ""went through... ""I'm not really  ""sure why that is""'cause I'm just ""a kid!@",
        "I heard that you""can press SELECT""to look at the  ""island map...   ""But, I don't    ""understand what ""they mean by    ""that...@",
        "When you're     ""running out of  ""Hearts, you'd   ""better enter a  ""house or cave...""Why?  I have no ""idea, I'm just a""kid!@",
        "Hey, dude! What ""do you think of ""Marin?  Uhh...  ""I don't know,   ""I'm just a kid!@",
        "Where are you   ""from, brother?  ""...Outside the  ""island?  What is""'outside?'  I've""never thought   ""about it...@",
        "The giant egg on""top of Tamaranch""Mountain?  They ""say the Wind    ""Fish is sleeping""inside of it... ""Why?  I don't   ""know either...@",
        "Dude!  You're   ""asking me when  ""we started to   ""live on this    ""island?  What do""you mean by     ""'when?'  Whoa!  ""The concept just""makes my head   ""hurt!@",
        "Marin? She likes""to go stare at  ""the ocean all by""herself...  Why?""Hey, I'm just a ""kid, don't ask  ""me!@",
        "Hey... Where're ""you two going   ""together?  Hunh?""Uh, I didn't    ""mean anything...""I'm just a kid!@",
        "Hey hey, bro!   ""About the Dream ""Shrine there... ""They say there's""something good  ""inside... ...   ""I better not say""anything else   ""as I'm just a   ""kid!@",
        "Hunh?!  Marin's ""not with you?   ""What happened to""her?@",
        "WHOA! That's a  ""big one! Hey,   ""photo guy! Can  ""you take a      ""picture of this?@",
        "I have a        ""feelin' that    ""I'll catch a big""fish again.@",
        "If you keep me a""secret, I'll    ""tell you some-  ""thing useful.   ""Go to Toronbo   ""Shores, use the ""magnifying glass""and you will    ""find someone    ""like me.@",
        "Tsk tsk...  What""a shame...@",
        "Oh thank you!   ""You are indeed a""generous person!""Ah!  I will give""you this in     ""return!@",
        "You traded your ""<yoshi> for <ribbon>!  Maybe ""you can trade   ""the ribbon for  ""something else!@",
        "Because they all""look alike, even""I am sometimes  ""confused. . .   ""By the way, my  ""baby wants a    ""Yoshi Doll.     ""I saw one at the""Trendy Game,    ""but I couldn't  ""get it.@",
        "Oh!  Will you   ""give that doll  ""to my baby?!    ""    Yes  No<ask>",
        "Because they all""look alike, even""I am sometimes  ""confused...     @",
        "Ahem!  Really, I""must insist that""you not bring   ""that awful beast""in here!  Leave ""that creature   ""outside and then""we can talk!    ""Good Bye!@",
        "You want to know""about that      ""ghost? I'll bet ""he's happy      ""thanks to you.  ""Are you ready   ""for a picture?@",
        "Ho ho ho!       ""I really appre- ""ciate what you  ""did for my poor,""precious BowWow!""You are such a  ""nice boy!  How  ""can I ever repay""you?  I know... ""  SMOOOOOOOCH!  ""You got a reward""from Madam Meow-""Meow... ... ... ""L-l-lucky!@",
        "Ho ho ho!  My   ""BowWow is so    ""proud of his    ""fine fur coat!@",
        "AIEEEEEEEE!     ""It's terrrrible!""My BowWow was   ""dognapped by... ""Mo-mo-MOBLINS!! ""OHHH!  AHHHH!   ""Please! Somebody""help my poor    ""BowWow!!@",
        "Oh thank you!   ""I'm so happy you""brought my baby ""back! Now, would""you be a dear   ""and take him for""a walk? It would""really help me  ""out a lot!  You ""will?!  Thanks!@",
        "Well... I pretty""much stick to   ""myself, me and  ""my letters...   ""My name's Write!""The only thing I""don't like about""my hobby is that""I never receive ""a response...@",
        "What's this?!  A""letter for me?! ""I'm so happy!   ""...And look! The""letter came with""a photograph!@",
        "Mmm... She's so ""beautiful...    ""I must give you ""something for   ""your trouble... ""Hmm...  Well, it""looks like all I""have is this    ""broom... how'll ""that be?        ""    Fine No...<ask>",
        "You got a Broom ""as your reward  ""from Mr. Write! ""But that photo  ""was not of...@",
        "Please! I really""must insist you ""have this <broom>!    ""    Okay No Way<ask>",
        "Oh boy!  Letter ""writing is such ""a great hobby!@",
        "Hello!  I'm     ""writing back to ""Christine now!@",
        "Salutations!    ""You wouldn't    ""know by the look""of me, but I    ""used to live in ""the castle! My  ""servants went   ""berserk and I   ""was forced to   ""flee to my      ""villa... So, you""want the key to ""Ukuku Prairie,  ""do you?  I may  ""be able to help ""you...  Let's   ""make... a deal, ""shall we? I want""you to retrieve ""the Golden Leaf ""I left behind in""the castle when ""I fled...       ""    Okay No Way<ask>",
        "I am impressed. ""There are five  ""leaves in all.  ""Remember to buy ""a shovel on your""way back.@",
        "Well, I never!  ""I thought you   ""looked cowardly,""but...  Please, ""leave me... just""get out here!@",
        "Ahh!  Tres Bien!""I see you have  ""recovered all of""the leaves! Now,""move this box   ""and you will    ""find your       ""reward!@",
        "I am forever in ""your debt for   ""getting my      ""leaves back!@",
        "Ah!  Bonjour!   ""#####, for the  ""love of justice,""and my own sake,""you must find   ""all the leaves!@",
        "Er...Uh...Hmm...""How to say...   ""Please call...  ""Outside...  ... ""It seems that   ""old man Ulrira  ""is a shy guy,   ""in person...@",
        "'BRRING! BRRING!""Hello!  It's me,""Ulrira!  Ask me ""anything about  ""the island!  If ""you get lost,   ""give me a call! ""Bye! CLICK!'@",
        "'BRRING! BRRING!""Hello, this is  ""Ulrira! ...Well,""most Moblins    ""live in the Mys-""terious Forest, ""but some live in""the caves of Tal""Tal Heights...  ""I hope that is  ""what you wanted ""to know! CLICK!'@",
        "'BRRING! BRRING!""Yes, this is    ""Ulrira.  The    ""Indigestible    ""Flowers of      ""Goponga Swamp...""Those flowers   ""are BowWow's    ""favorite.  Why  ""don't you take  ""him for a walk  ""there?  CLICK!'@",
        "'BRRING! BRRING!""Hi, it's Ulrira!""...Have you met ""everyone on the ""island?  There's""a man named     ""Richard who     ""lives in Pothole""Field, southeast""of the village. ""Why not pay him ""a visit?  That's""all I can tell  ""you for now!    ""Bye!  CLICK!'@",
        "'BRRING! BRRING!""Old man Ulrira  ""here! ...Do you ""like bananas?   ""Try talking to  ""people in the   ""village again!  ""Bye!  CLICK!'@",
        "'BRRING! BRRING!""Ulrira speaking!""You know, there ""is a library in ""the village that""might have some ""good information""for you!  Talk  ""to you later!   ""CLICK!'@",
        "'BRRING! BRRING!""Ya, it's Ulrira!""You say you     ""haven't found   ""all five Golden ""Leaves? Go ask  ""the crow at the ""castle. I'm sure""he can help you.""Bye!            ""CLICK!'@",
        "'BRRING! BRRING!""Ulrira here! ...""Shovel...  Did  ""you purchase a  ""shovel?  You may""find something  ""if you dig here ""and there!  Bye!""CLICK!'@",
        "'BRRING! BRRING!""Ya, it's Ulrira!""The cave in the ""Ukuku Prairie is""the key!  Yes, I""mean the key    ""cave, no pun    ""intended!  Bye! ""CLICK!'@",
        "'BRRING! BRRING!""Hi, this is     ""Ulrira!  In the ""Yarna Desert,   ""which is located""in the southeast""of the island,  ""you will find   ""something called""the Angler Key. ""Hmmm... How much""more obvious do ""I have to be?   ""Bye! CLICK!'@",
        "'BRRING! BRRING!""This is Ulrira! ""Now you're being""haunted by a    ""ghost?! Well,   ""how about taking""him where he    ""wants to go?    ""Bye! CLICK!'@",
        "'BRRING! BRRING!""Hi, it's Ulrira!""The Catfish's   ""mouth is wide   ""open?  It sounds""like a great    ""place to dive!  ""Bye!  CLICK!'@",
        "'BRRING! BRRING!""Ulrira here! ...""Have you been to""the Face Shrine?""It is north of  ""Animal Village. ""That is a very  ""interesting     ""ruin... CLICK!'@",
        "'BRRING! BRRING!""Hi, it's Ulrira!""Have you heard  ""of the Flying   ""Rooster of Mabe ""Village?  In the""good old days,  ""it used to give ""us rides if we  ""held it above   ""our heads... Now""it is lying     ""under the       ""Weathercock...  ""Is that useful  ""for you?  I hope""so! Bye! CLICK!'@",
        "'BRRING! BRRING!""Hi, it's Ulrira!""The head of the ""turtle is in    ""your way?  Put  ""life into it and""it will move!   ""It's true! True!""Bye!  CLICK!'@",
        "   ...SWAMP...  "" A path opens...""in the blooms...@",
        "  ...PRAIRIE... ""  ...PRAIRIE... "" The Prairie is ""     waiting...@",
        "...WATERFALL... ""It is hidden in ""the waterfall...@",
        "    ...BAY...   ""Your road goes  ""into the bay... @",
        "   ...SHRINE... ""An island secret""in the shrine...@",
        " ...MOUNTAIN... ""Something calls ""  ...from the   ""  mountains...@",
        "  ...OCARINA... ""The music of the""Ocarina leads...@",
        "    ...EGG....  ""The Egg on the  ""mountain calls!@",
        "Then YOU sweep  ""the island!@",
        "YAHOO!   I'm    ""fine, and you?!@",
        "YAHOO!  I worked""too hard and now""my broom is worn""to the handle!@",
        "YAHOO!  YAHOO!  ""A new broom?!   ""For me?  It is, ""isn't it?!      ""    Yes  No<ask>",
        "Okay!  In return""you can have    ""this fishing    ""hook I found    ""when I swept by ""the river bank!@",
        "You exchanged <broom> ""for the fishing ""hook <fishhook>!  What   ""will the fishing""hook become?@",
        "YAHOO!  A new   ""broom!  Superb!@",
        "Kiiiki!  What?! ""All right, mutt!""Let's battle!!@",
        "Chi-kiita! Chi- ""kiita!  Kiki the""monkey!  Hungry!""Kiki the monkey!@",
        "    <bananas>!    <bananas>!    ""Oooh! Ooh! Kiki!""Monkeys!  Come! ""Repay him! Kiki!@",
        "Monkey business!""Done!  Bye bye! ""Oooh!  Kiki!@",
        "You found a     ""stick a monkey  ""left behind...  ""You take it!@",
        "    <bananas>!    <bananas>!    ""  Oooh!  Oooh!  "" Give to Kiki!? ""    Yes  No!<ask>",
        "You don't know  ""the proper      ""etiquette when  ""dealing with a  ""lady, do you?   ""You should have ""brought flowers ""or something,   ""then I might be ""more inclined to""talk with you...""Oh yes, in my   ""case, hibiscus  ""are best...@",
        "Oh, you brought ""me a hibiscus!  ""How sweet! Well,""since you are   ""such a gentleman""I have a request""to make of you. ""Will you listen?""    Yes  No<ask>",
        "I would like you""to take this    ""letter to a Mr. ""Write who lives ""on the border of""the Mysterious  ""Forest, please!@",
        "...Is that so?  ""And I thought   ""you were a      ""gentleman...@",
        "You traded <flower2> for""a goat's letter ""<letter>!  ...Great!?@",
        "You know, some- ""times I can't   ""help eating a   ""delicious piece ""of paper, even  ""if it's a letter""to my darling   ""Mr. Write... How""embarrassing!@",
        "You've saved    ""BowWow!  What a ""fearsome beast!@",
        "Wow! The Rooster""has recovered!  ""He seems very   ""friendly!@",
        "'BRRING! BRRING!""Ya, it's Ulrira!""My wife went to ""the Animal      ""Village and left""me all alone.   ""Can you tell    ""her to come home""as soon as she  ""is done         ""cleaning?       ""Bye!            ""CLICK!'@",
        "Grandma's not   ""here. She's in  ""the Animal      ""Village. That's ""what Grandpa    ""Ulrira said on  ""the phone!@",
        "Yep, Papahl got ""lost, just like ""he said!  Now, I""am so famished I""can't move!  Can""you give me some""vittles?        ""    Yes  Nope<ask>",
        "You're one cold ""hombre...@",
        "This <pineapple> is so    ""delicious!  I'm ""going to eat the""<pineapple> right now!    "" Bon Appetit!@",
        "AH!  This isn't ""meant to be a   ""reward...  Here,""take this <flower2>!    ""It's a hibiscus!@",
        "You traded the <pineapple>""for the <flower2>!@",
        "Delicious!  Yum!""I'm filled with ""energy, now!@",
        "I've got to say,""thanks again!@",
        "Yep, Papahl got ""lost, just like ""he said!  Now, I""am so famished I""can't move!  Can""you give me some""vittles?        ""    Nope Can't<ask>",
        "She's had an    ""awful tragedy   ""in the house    ""across the way! ""It's just awful,""and all I can do""is sweep!@",
        "I am the spirit ""of the mansion. ""I have been     ""waiting for     ""someone to      ""overcome the    ""darkness. Find  ""all the secret  ""shells and go   ""through the     ""gate to receive ""the ultimate    ""sword!@",
        "Hmmm. No        ""response. You   ""must not have   ""enough shells.@",
        "My job here     ""is finished.@",
        "Hey you! Have   ""you been to the ""Camera Shop in  ""Tal Tal Heights?""Iyoung people   "" like to go ther""eand take       "" pictures of    "" themselves.    "" Seems kinda    "" funny to me.@",
        "Step right up   ""and get your    ""souvenir photo!@",
        "Good job!       ""Use it on your  ""enemies and see ""what happens.   ""If you run out, ""go to the for-  ""est, pick some  ""mushrooms, and  ""I will make you ""more.@",
        ". . . .! I can't""move! But I am  ""still all right.""Your little     ""sword won't     ""break this      ""bottle!@",
        "Make-up! Jewels!""Dresses!  I want""it all!  Sigh...""And some new    ""accessories     ""would be nice...@",
        "Make-up! Jewels!""Dresses!  I want""it all!  Sigh...""And some new    ""accessories     ""would be nice...""Oh! That Ribbon!""I need it!  Will""you trade for my""dog food?       ""    Yes  No!<ask>",
        "You exchanged <ribbon> ""for <dogfood>! It's full""of juicy beef!@",
        "Lucky!  Thanks! ""Well, here's    ""your <dogfood>!@",
        "Eh?!  I can't   ""believe it!  You""are the worst!!@",
        "I am Manbo,     ""child of the Sun""Fish!  Have you ""got an Ocarina? ""    Yes  No<ask>",
        "Very well...    ""Glub Blub Bloop!@",
        "Ahaha!  Then I  ""can teach you my""song! Bloop!@",
        "You've learned  ""Manbo's Mambo!  ""When you get out""of the water,   ""play it!@",
        "I am Manbo,     ""child of the Sun""Fish!  When you ""play my Mambo,  ""you can warp to ""Manbo Pond!  Try""this tune in the""dungeons, too!  ""Cha-cha-cha!@",
        "Aha... You don't""have an Ocarina,""so...Glub glub!@",
        "Chickens these  ""days don't have ""the fighting    ""spirit they used""to!  In the old ""days, they could""fly, flap flap! ""But now, see?   ""Cluck cluck!@",
        "Wow!  Amazing!  ""That rooster is ""actually flying!""It's just like I""said, eh?  Have ""you tried to    ""hold him over   ""your head? Cluck""Cluck!@",
        "Wooo!  Finally! ""This flying     ""rooster is the  ""greatest!@",
        " Here Sleeps The"" Flying Rooster@",
        "Iz zat zee      ""Mermaid scale?  ""I can't use it  ""now. I have to  ""werk on zis     ""drawing. You    ""should go finish""zee mermaid     ""statue for me.@",

        "Ennh?  Who's    ""this suspicious-""looking runt?!  ""Okay boys, let's""get ridda him!@",
        "You must be an  ""assassin sent by""Madam MeowMeow  ""to rescue the   ""mutt!  You came ""here to get me, ""but it is I who ""will get you!!@",
        "Oh, #####.  I   ""often come to   ""this village to ""sing, too!  It  ""seems that just ""about everyone  ""loves my 'Ballad""of the Wind     ""Fish!'  #####,  ""what is your    ""favorite song?@",
        "Please, don't   ""ever forget this""song...or me...@",
        "Thank you for   ""everything!     ""#####, you are  ""the kindest boy ""I know.  One day""I made a wish to""the Wind Fish...""What was the    ""wish?  It was...""No, it's secret!@",
        "#####, some day ""you will leave  ""this island...  ""I just know it  ""in my heart...  ""...Don't ever   ""forget me... If ""you do, I'll    ""never forgive   ""you!@",
        "... ... ... ... ""It seems to be  ""totally absorbed""in Marin's song!@",
        "They say the    ""'Ballad of the  ""Wind Fish' is a ""song of awaken- ""ing.  I wonder, ""if the Wind Fish""wakes up, will  ""he make my wish ""come true?@",
        "Eh?  You want me""to go in there? ""No, I think I'll""wait out here...""Take care of    ""yourself, #####!@",
        "Ahhh!  Ahhh, you""are a bad boy,  ""#####!@",
        "Here's some     ""bonus treatment!""Behold!  Your   ""Hearts are full!@",
        "Ya, I am Schule ""Donavitch!  Zee ""mermaid statue  ""by zee bay iz my""masterpiece! ...""To tell you zee ""truth, zis werk ""iz not complete!""Zee art, it'z...""difficult for   ""you to grasp, iz""it not?@",
        "  THE MOURNING  ""     MERMAID    ""    By SCHULE   ""? ...A scale is ""missing...@",
        "Seashell Mansion@",
        "Entrance to     ""  Yarna Desert <right>@",
        "   Mysterious   ""     Forest     "" (It's a little "" bit mysterious)@",
        "Do you want to  ""challenge the   ""river rapids on ""a raft?  Proceed""to the office at""once, please!@",
        "East <right> Ukuku    ""       Prairie  ""Farther East    ""  Animal Village@",
        "Mt. Tamaranch   @",
        "<right> Tail Cave     ""<down> Toronbo Shores@",
        "<right> Gopongo Swamp ""<down> Mysterious    ""  Forest@",
        "Beware of floors""with cracks!  A ""heavy person    ""should not stand""on them!@",
        "Telephone Booth @",
        "     DANGER!    ""    Keep out!   ""(Except BowWow)@",
        "<down> GO THIS WAY@",
        "<up> GO THIS WAY@",
        "<right> GO THIS WAY@",
        "<left> GO THIS WAY@",
        " TRY AGAIN FROM ""   THE START@",
        "GREAT!  YOU DID ""IT!  YOUR REWARD""IS <right> THIS WAY!@",
        "GONE ON TOUR    ""         MAMU@",
        "<right> Crazy Tracy   ""<down> Manbo's Pond@",
        "<right> Animal Village""<down> Martha's Bay@",
        "<right> Welcome to the"" Animal Village!@",
        "<right> Cemetery      ""<down> Ukuku Prairie @",
        "You're close to ""Tal Tal Heights.""The Camera Shop ""is nearby.@",
        "<right> Tamaranch Mt. ""<left> Goponga Swamp @",
        "MUSIC, THE FISH ""STIRS IN THE EGG""YOU ARE THERE...@",
        "THE WIND FISH IN""NAME ONLY, FOR  ""IT IS NEITHER.@",
        "IN SOIL SLEEPS  ""SECRETS, BENEATH""YOUR SOLES...@",
        "IN SOIL SLEEPS  ""SECRETS, BENEATH""YOUR SOLES...@",
        "AROUND HERE,    ""SECRETS ARE NIGH@",
        "SECRETS ARE LIKE""WATER WHEN IT   ""COMES TO BRIDGES@",
        "NOW YOU NEED    ""LOOK FAR FOR    ""A SECRET...@",
        "THE WIND FISH   ""SLUMBERS LONG...""THE HERO'S LIFE ""GONE...@",
        "SEA BEARS FOAM, ""SLEEP BEARS     ""DREAMS. BOTH END""IN THE SAME WAY ""CRASSSH!@",
        "Oh?!  #####, I  ""see ya have a   ""nice stick...   ""Can I borrow it ""for a second?   ""    Can  Can't<ask>",
        "<stick> became the    ""honeycomb <honeycomb>!    ""You're not sure ""how it happened,""but take it!@",
        "Hmmm, #####, you""are mean!@",
        "Beware of Sea   ""Urchins!  Don't ""touch them with ""your bare hands!@",
        "I was hungry    ""somethin' fierce""so I went and   ""got bananas at  ""the beach...    ""#####, if you   ""want some, you  ""should go and   ""get some!@",
        "Welcome to      ""Sale's House O' ""Bananas!  I'm   ""Sale, this is my""house! Actually,""my hobby is col-""lecting rare and""unusual canned  ""food. My brother""is an artist, so""I guess strange ""hobbies run in  ""the family!@",
        "What's that you ""have?!  It's    ""canned food! For""heaven's sake,  ""man, give that <dogfood>""to ME!!  PLEASE!""He's hysterical!""What do you do? ""    Give Don't<ask>",
        "Oh thank you!   ""I'll take that!@",
        "I don't suppose ""it would do any ""good to beg?    ""Well, if you    ""change your     ""mind, tell me.@",
        "  MUNCH MUNCH!! ""... ... ... ... ""That was great! ""I know it's not ""a fair trade,   ""but here's some ""bananas! YUM...@",
        "You gave him <dogfood>  ""and got bananas ""<bananas> in return!    ""Good deal!@",
        "Thank you again!""That was yummy!@",
        "Hey friend! Have""you ever ridden ""the rapids on a ""raft?  You can, ""near Tal Tal    ""Heights!  You   ""ought to try it!@",
        "Rik'm rak'm! I  ""ran out of      ""ingredients!  If""I had honey, I  ""could make this ""fit for a king!@",
        "Hi ho! Hey you! ""Is that possibly""a <honeycomb> you have?   ""I just ran out! ""Will you swap it""for a pineapple?""    Yes  No<ask>",
        "You exchanged <honeycomb> ""for <pineapple>!  It's not""as sweet, but it""is delicious!   @",
        "That's a crying ""shame, but I    ""realize those   ""are a rare      ""delicacy!@",
        "Hi ho! Yeah, I  ""know, that tub  ""of goo is asleep""right in the way""to Yarna Desert!""Once he's asleep""he won't budge  ""for a loooooonng""time.  But hey! ""Take Little     ""Marin and wake  ""him up with her ""song!  That slob""would wake up   ""with a jump if  ""he heard her    ""sing, for sure! ""Heh heh heh!@",
        "My ultimate plan""is to open a    ""branch in Mabe  ""Village!@",
        "HI HO!  Little  ""Marin!  Welcome!""... ... ... ... ""Oh, shucks!  You""are here too... ""Sorry...@",
        "Oh, #####, I'm  ""glad you found  ""this place.     ""Will you stay   ""and talk to me  ""for a while?    ""    Yes! No...<ask>",
        "Okay, I'll just ""watch the waves ""for a while...@",
        "At the beach... "" Marin  <marin>@",
        "I wonder where  ""these coconut   ""trees come from?""...Tarin says   ""there is nothing""beyond the sea, ""but I believe   ""there must be   ""something over  ""there...  When I""discovered you, ""#####, my heart ""skipped a beat! ""I thought, this ""person has come ""to give us a    ""message...@",
        "... ... ... ... ""... ... ... ... ""If I was a sea  ""gull, I would   ""fly as far as I ""could!  I would ""fly to far away ""places and sing ""for many people!""...If I wish to ""the Wind Fish,  ""I wonder if my  ""dream will come ""true... ... ...@",
        "Hey!  Are you   ""listening?      ""#####, are you  ""listening to me?""    Yeah No...<ask>",
        "I want to know  ""everything about""you...Err...Uhh,""Ha ha ha ha!@",
        "Hunh? The walrus""wants me to go  ""to him?  It     ""doesn't matter, ""I will go with  ""you to him...@",
        "Unnnngh! Owwwww!""... ... ... ... ""I've sure lost  ""my taste for    ""honey!@",
        "Humph! Your head""is always in the""clouds! Will you""please listen to""me next time?!@",
        "Ha! That's all  ""you've got?!    ""Get ready for   ""THIS!@",
        "ZZZ ZZZ ZZZ ZZZ "" ... <marin> ... <marin> ...@",
        "Yes, it's that  ""lazy walrus!    ""Shall we give   ""him a little    ""surprise?       ""    Yes  No...<ask>",
        "Aha ha ha!  Wow!""He certainly    ""woke with a     ""start!@",
        "Hunh?  Oh, he's ""calling me...   ""It's the same as""always... Ha ha!@",
        "You're right, it""would be mean to""wake him up now!""Let's let him   ""sleep some more!@",
        "#####, I'm going""to the Animal   ""Village!  Please""drop by, okay?@",
        "Arfh! Arfh! Arf!"" <marin>  <marin>!  <marin>   <marin>!  ""..... <link>?? @",
        "It's no use,    ""little buddy!  A""fish took my    ""hook... I keep  ""casting my line ""into the water, ""but I haven't   ""got a bite... I ""thought this    ""would happen...@",
        "Oh! What is that""you have in your""hand?  It's not ""a fishing hook, ""is it?  You had ""better let me   ""have it.  I'll  ""give you my next""catch if you let""me have it...   ""    Okay No<ask>",
        "Keep your eyes  ""open and watch  ""a pro at work.@",
        "You should be   ""more kind to me!""I thought we    ""were buddies!@",
        "My, that's a    ""BIIIIG one!@",
        "The <fishhook> became a  ""necklace <bra>!     ""L-l-lucky!@",
        "I can't wait to ""see what I'll   ""catch next!@",
        "My husband is   ""lost in the     ""woods! Please   ""go find him!@",
        "Hey, you can see""me?! You must   ""have a magnify- ""ing glass. I'm  ""not a trouble   ""maker. I just   ""want to live in ""peace.@",
        "When I was swim-""ming in the bay,""the waves took a""very important  ""necklace from   ""around my neck! ""If you find it, ""I will let you  ""take a scale    ""from my tail!   @",
        "I have already  ""looked around   ""here!@",
        "Ahh!  That's it!""That's my neck- ""lace!  Give it! ""Give it back!  I""will give you a ""scale as I said!""    Give Keep<ask>",
        "Promise!  You'll""only take one!@",
        "You are heart-  ""less and cruel!@",
        "You returned the""necklace <bra> and  ""got a scale <scale> of""the mermaid's   ""tail.  How will ""you use this?@",
        "I'll call this  ""'I Was Very     ""Afraid.' Smile!@",
        "An artist once  ""asked me to pose""for him, and he ""wanted a scale, ""too...  Can the ""legend of the   ""Magnifying Lens ""be true...?@",
        "Hi there! It's  ""me, the photo-  ""grapher! You say""Zora is in the  ""house? I HAVE to""take a picture  ""of that. I'll   ""call it 'I Found""Zora.'@",
        "Richard's Villa @",
        "Kanalet Castle  ""10 Min. <right> <up>@",
        "Kanalet Castle  ""5 Min. <right>@",
        "Kanalet Castle  ""50 Paces <up>@",
        "'BRRING! BRRING!"" BRRING! CLICK! ""Yeees!  It's the""Bucket Mouse!   ""Thanks for call-""ing! ...Well... ""CLICK!'  ??? ...""You must have   ""dialed a wrong  ""number...@",
        "Oh!  It's a big ""one!  And it has""a Piece of      ""Heart, too!  You""get a 20 Rupee  ""prize on top of ""that! Try again?""    Yes  No<ask>",
        "Oh!  It's a big ""one!  And it has""a Piece of      ""Heart, too!  You""have completed  ""another Heart   ""Container!  On  ""top of that, you""get a 20 Rupee  ""prize! Want to  ""try again?      ""    Yes  No<ask>",
        " 'How To Handle ""   Your Shield  ""   Like A Pro!' ""Read this book? ""    YES  NO<ask>",
        "'If you hold the""Button down, you""can defend your-""self from enemy ""attacks, and you""can flip some   ""enemies, too... ""Besides the     ""standard shield ""there is also a ""mirrored variety""which can defend""against beams!'@",
        " 'Selecting The ""   Item That's  ""  Right For You'""Read this book? ""    YES  NO<ask>",
        "'You can select ""your favorite   ""item for the A  ""and B Buttons on""the Sub-Screen. ""Using different ""items, you can  ""fight without a ""sword!  Try many""different things""to find what's  ""right for you!'@",
        " 'Auto Map and  ""Memo Guide Book'""Read this book? ""    YES  NO<ask>",
        "'You can see an ""island map by   ""pressing the    ""SELECT Button.  ""The dark parts  ""of the map are  ""places you have ""not yet visited.""Move the cursor ""and press the A ""Button to get   ""more information""about an area,  ""or to replay the""message you got ""there...'  Ahhh!""How convenient!@",
        " 'Secrets Of The"" Whirling Blade'""Read this book? ""    YES  NO<ask>",
        "'The Whirling   ""Blade technique ""has been handed ""down from gener-""ation to gener- ""ation by the    ""family of the   ""hero. To use it,""hold down the   ""Sword Button and""build up your   ""power.  When you""have enough, you""can release the ""Button!  Can you""master this?'@",
        "'The Properties ""  Of Warp Holes'""Read this book? ""    YES  NO<ask>",
        "'There are some ""Warp Holes on   ""Koholint Island.""You can warp to ""and fro using   ""these holes.  If""you jump into   ""the Warp Hole   ""at which you    ""arrived, you    ""will go to the  ""next one in the ""sequence.  You  ""can only warp to""a hole you have ""seen with your  ""own eyes...'@",
        "'Fun With Bombs'""Read this book? ""    YES  NO<ask>",
        "'After you put a""Bomb down, you  ""can pick it up  ""by pressing the ""Button again.   ""You can then    ""throw it by     ""pushing the     ""Button one more ""time.  Did you  ""know that?'@",
        "   'Atlas Of    ""Koholint Island'""You can move the""cursor and look ""up the name of a""place...  Do you""want to look at ""this map?       ""    Look Don't<ask>",
        " 'Dark Secrets  ""  And Mysteries ""   Of Koholint' ""Do you really   ""want to read it?""    YES  NO<ask>",
        "Gasp! Wha-What's""this! ... ...   ""You can't read  ""the tiny print  ""without the aid ""of a magnifying ""glass...@",
        "...my grave...  ""...take me...   ""...my grave...@",
        "...the house... "" ...take me...  ""...the house... ""...at the bay...@",
        "...N-N-No!...   ""...N-not there!@",
        "   ...Here!...  ""   ...enter...  "" ...my house...@",
        " ...Nostalgia..."" ...unchanged..."" ...boo hoo...@",
        "  ...Enough...  "" ...cemetery... ""  ...take me... "" ...my grave...@",
        "...Thank you... "" ...a jar...    ""...in my home...""...look inside..""...bye...bye...@",
        "Round and round,""the passageways ""of the Egg...   ""<left> <left> <up> <right> <right> <up> <left> <up> ""??  ...Hmmmmmm, ""this book reeks ""of secrets...@",
        "Round and round,""the passageways ""of the Egg...   ""<right> <up> <up> <right> <up> <up> <right> <up> ""??  ...Hmmmmmm, ""this book reeks ""of secrets...@",
        "Round and round,""the passageways ""of the Egg...   ""<left> <up> <right> <up> <left> <up> <right> <up> ""??  ...Hmmmmmm, ""this book reeks ""of secrets...@",
        "Round and round,""the passageways ""of the Egg...   ""<right> <right> <right> <right> <up> <up> <up> <up> ""??  ...Hmmmmmm, ""this book reeks ""of secrets...@",
        "...You're late! ""I thought you'd ""never come back!@",
        "...EEEK!  You're""hurt!  Arrrgh!  ""Don't be so     ""reckless!@",
        "#####! You're   ""back!  Are you  ""hurt?@",
        "...You idiot!   ""I told you this ""would happen... ""Eh?!  What?  I  ""didn't say any- ""thing, really!@",
        "Hey buddy!  It's""serious!  Yeah, ""really serious!!""Yeah, it is!    ""The Moblins came""to the village! ""Yeah, that's    ""right!  A whole ""gang of Moblins!""Then... It's for""real!  They all ""went to the     ""house...  Yeah, ""that house, and ""then they did   ""something at Bow""Wow's house!!   ""It was a really ""bad scene, with ""the M-m-moblins!""So, I mean, ahh!""... ... ... ... ""... ... ... ... ""It might be     ""faster to find  ""out for yourself""what happened!@",
        "I found a good  ""item washed up  ""on the beach... ""I'll trade it to""you for what you""have in your B  ""Button...       ""    Okay No<ask>",
        "Okay, let's do  ""it!  When you   ""don't want the  ""Boomerang any   ""more, come back!@",
        "Oh, yeah, uh... ""okay, whatever.@",
        "You got the     ""Boomerang in    ""exchange for the""item you had.@",
        "Give me back the""Boomerang, I beg""you! I'll return""the item you    ""gave to me!     ""    Okay Not Now""<ask>",
        "The item came   ""back to you. You""returned the    ""Boomerang.@",
        "Ah... Don't give""me that item... ""How about some- ""thing else?@",
        "'BRRING! BRRING!""Ya, it's Ulrira!""You haven't     ""found the 5     ""Golden Leaves?  ""Keep an eye on  ""the ones you    ""have. Someone   ""might try and   ""take 'em! Bye!  ""CLICK!'@",
        "'BRRING! BRRING!""Ya, it's Ulrira!""You haven't     ""found the 5     ""Golden Leaves?  ""Try bombing sus-""picious places. ""Hope that helps.""Bye!            ""CLICK!'@",
        "'BRRING! BRRING!""Ya, it's Ulrira!""You haven't     ""found the 5     ""Golden Leaves?  ""Go scare that   ""crow by the     ""castle and see  ""if that helps!  ""Bye!            ""CLICK!'@",
        "'The Travels of ""#####' Do you   ""want to look at ""your album?     ""    Look Don't<ask>",
        "Which picture   ""would you like  ""to see? Use <dpad> to""select, then    ""press the A     ""Button!@",
        "You are near the""Eagle's Tower.  ""Beware of the   ""bird!@",
        "Hi, #####. You  ""know I love to  ""take pictures.  ""Wouldn't this   ""old castle make ""a great photo?@",
        "Hunh?  A keyhole""here?  It says, ""'Tale Keyhole'@",
        "Hunh?  A keyhole""here?  It says, ""'Slime Keyhole'@",
        "Hunh?  A keyhole""here?  It says, ""'Angler Keyhole'@",
        "Hunh?  A keyhole""here?  It says, ""'Bird Keyhole'@",
        "Hunh?  A keyhole""here?  It says, ""'Face Keyhole'@",
        "Somebody, HELP!@",
        "Hey!  #####!    ""Some monsters   ""put me up here! ""What should I   ""do?!  I'm afraid""of heights!!@",
        "Yow!  That was a""surprise! #####,""thank you!@",
        "... ... ... ... ""... ... ... ... ""Say... #####... @",
        "Uhh... I don't  ""know how to say ""this... but...@",
        "Hunh?!  Tarin??!""... ... ... ... ""Uh... Nevermind,""I... I gotta go!@",
        "MAAAAAAARINNNN!!@",
        "Nothing yet?! I ""grow tired of   ""waiting. I want ""those Golden    ""Leaves delivered""soon!           ""Courage like    ""this deserves a ""photo, don't you""think?@",
        "Hey, Marin and  ""#####! Are you  ""taking pictures?""You should take ""pictures of     ""everyone,       ""including me.@",
        "I use this to   ""take pictures.  ""Are you ready?  ""Say 'mushroom!'@",
        "OK, I'm done.   ""I'll go home    ""now.@",
        "'BRRING! BRRING!""This is Ulrira! ""Oh, I heard from""grandma that    ""there is some-  ""thing hidden    ""behind the falls""in the Tal Tal  ""Mountains.  Does""that help?  Bye!""CLICK!'@",
        "'BRRING! BRRING!""Ulrira here...  ""Yes, when I was ""just a lad, I   ""recall seeing a ""high tower in   ""the mountains!  ""You should go   ""there!  Is that ""helpful for you?""Bye! CLICK!'@",
        "'BRRING! BRRING!""Hello, this is  ""Ulrira speaking!""#####, it's time""for you to face ""the Egg on Mt.  ""Tamaranch!  Be  ""careful, #####! ""Bye!  CLICK!'@",
        "'BRRING! BRRING!""This is Ulrira! ""You're lost in  ""the Egg?  Hmmmm.""No sir, I can't ""help you on that""one.  How about ""the library?    ""And hey, don't  ""stop calling me ""because I didn't""know one little ""answer!  CLICK!'@",
        "'BRRING! BRRING!""Ulrira at your  ""service!  Oh?   ""You should take ""BowWow home now,""Madam MeowMeow  ""would appreciate""it! Bye! CLICK!'@",
        "'BRRING! BRRING!""Yeah, this is   ""Ulrira!  You are""starting to like""music, eh?      ""Well, a frog    ""named Mamu, who ""lives in the    ""Signpost Maze,  ""might know some ""new songs, but  ""he charges a lot""to play them!   ""Bye!  CLICK!'@",
        "'BRRING! BRRING!""Hi, it's Ulrira!""You are doing   ""great!  Your    ""efforts will end""soon... By the  ""way, have you   ""visited the Hen ""House on the    ""mountain?  There""is a cave nearby""with something  ""important in it.""Bye!  CLICK!'@",
        "'BRRING! BRRING!""Ulrira speaking!""Are your enemies""too strong for  ""you?  In that   ""case, you better""collect all the ""Seashells...Just""believe in your-""self and do your""best!  CLICK!'@",
        "'BRRING! BRRING!""Ulrira here! ...""Go for it!      ""You're almost   ""there! I'm pull-""ing for you!    ""Bye!  CLICK!'@",
        "Go ahead and    ""take a picture  ""of me. Any angle""you like!@",
        "Yarna Desert?   ""There's a way to""get there to the""south, but you  ""might not be    ""able to get     ""through if that ""lazy walrus is  ""in the way!@",
        "Ahhh... Sigh... ""On such a nice  ""day, we need a  ""song from Marin!@",
        "Hey! Did ya know""Animal Village  ""and Mabe Village""are sister      ""cities?  Yes,   ""even though they""aren't large    ""enough to be    ""called cities...""Anyway, I heard ""from a very good""source that they""have a Dream    ""Shrine in Mabe, ""and that it has ""something good  ""inside...  Is   ""that true?@",
        "I can't go to   ""Mabe Village    ""because of all  ""the monsters.   ""I hope Marin    ""is all right.@",

        "Have you heard  ""of the Flying   ""Rooster?  They  ""say it lived in ""Mabe Village a  ""long time ago...""I wonder if it's""true...@",
        "Aaaah, Little   ""Marin... I want ""her to come back""again...Her song""is the best...@",
        "I dreamed that  ""I turned into a ""carrot last     ""night...  What  ""an odd dream...@",
        "Eh?  How can an ""animal talk?    ""How?  Hey, I'm  ""just a rabbit,  ""so I don't know!@",
        "Ahhh!  It's her!""Little Marin!!@",
        "If you have no  ""courage,then    ""you have no     ""strength.       ""Gravestones     ""won't move for  ""cowards.@",
        "I'm not afraid. ""I just decided  ""to wait at home.@",
        "This is my first""walk with you,  ""#####.@",
        ". . . . .@",
        "This cliff will ""be our secret   ""place. @",
        "Aren't you going""to say anything?@",
        "Oh how I love   ""pictures! Why   ""don't you take  ""a picture when  ""no one is       ""around? You can ""call it . . .@",
        "You've got the  ""Blue Clothes!   ""Your damage will""be reduced by   ""half!@",
        "You've got the  ""Red Clothes!    ""Your body is    ""full of energy! @",
        "Red for offense,""blue for        ""defense. Which  ""do you choose?  ""    RED  BLUE<ask>",
        "Are you sure?   ""    YES  NO<ask>",
        "The fairy queen ""is waiting for  ""you.@",
        "Do you have the ""powder? If not, ""you must go     ""back.@",
        "Our colors are  ""never the same! ""If I am red, he ""is blue! If he  ""is red, I am    ""blue! What color""is my cloth?    ""    Red  Blue<ask>",
        "BOO! I am no    ""weakling! Your  ""pitiful sword is""no match for me!@",
        "I am sorry, but ""this is the     ""Color Dungeon.  ""Only those with ""the power of    ""color may enter.""If you can tell ""who wears red   ""and who wears   ""blue, you may   ""enter.          ""Farewell.@",
        "Here is your    ""clue. Make      ""all the red     ""blue.@",
        "No,  no. Take a ""closer look and ""try again.@",
        "Don't tell      ""anyone.@",
        "Do you want to  ""read this book? ""    YES  NO<ask>",
        "New world of    ""color under the ""5 gravestones.  ""                ""   3<up>  4<right>  5<up>   ""   2<left>  1<down>       ""Try with all    ""your might. Open""a new path!     ""Whoever is      ""worthy receives ""the power of    ""color. I wonder ""what the world  ""of color is?@",
        "Welcome, #####. ""I admire you for""coming this far.""I will give you ""the power of    ""color. If you   ""want offense,   ""choose red. If  ""you want defense""choose blue.    ""Which power do  ""you want?       ""    RED  BLUE<ask>",
        "You fool! Your  ""sword won't     ""work! Try       ""something else!@",
        "What a greedy   ""fool! You want  ""more power?! A  ""buffoon like you""might as well   ""give up and     ""go home!@",
        "Relax and close ""your eyes.@",
        "I will now take ""you out.@",
        "Blue is safe.   ""Yellow is       ""caution. Red is ""danger.@",
        "Yellow is       ""caution. Red is ""danger,Take     ""your time.@",
        "Blue. Start     ""over. Yellow is ""caution. Red is ""danger.@",
        "Hey, that looks ""great! I'll call""it '##### Plays ""With BowWow!'   ""Now get closer  ""to BowWow!@",
        "Grrrr!@",
        "#####, get      ""closer!@",
        "Grrrr! Grrrr!!@",
        "Much closer! OK,""I'm ready.      ""Smile!@",
        "Grrrr! Grrrr!!  ""GRRRR!@",
        "Ha ha ha! Do it!""Do it!  Do it   ""moooore! ... ...""Hunh?  No, it's ""nothing... I    ""didn't mean it.@",
        "Not very good...""Eh?  What?  Did ""I say something?""No, you're hear-""ing things...@",
        "#####, do you   ""always look in  ""other people's  ""drawers?@",
        "Great!  Dig it! ""Dig it!  Dig to ""the center of   ""the earth!!@",
        "Whew!  What a   ""surprise!@",
        "Ohh!  I'm sorry!""Are you okay?!  ""#####?@",
        "Hey Mon!@",
        "You know me, I  ""like short names""the best...@",
        "It can display  ""millions of     ""polygons!@",
        "I definitely    ""need it, as soon""as possible!@",
        "Turn aside the  ""spined ones with""a shield...@",
        "First, defeat   ""the imprisoned  ""Pols Voice,     ""Last, Stalfos...@@",
        "Far away...     ""Do not fear,    ""dash and fly!@",
        "The glint of the""tile will be    ""your guide...@",
        "Dive under where""torchlight beams""do cross...@",
        "Enter the space ""where the eyes  ""have walls...@",
        "The riddle is   ""solved when the ""pillars fall!@",
        "Fill all the    ""holes with the  ""rock that rolls,""this (<dpad>) is the ""key!@",
        "If there is a   ""door that you   ""can't open, move""a stone block.@",
        "Make every block""design the same.""A new path will ""open.@",
        "Part of the     ""floor is raised.""Tap the blue    ""crystal.@",
        "To defeat the   ""black monster   ""with the hard   ""shell, feed him ""something ex-   ""plosive.@",
        "Poke suspicious ""parts of the    ""wall with your  ""sword and listen""to the sounds it""makes.@",
        "If you can't    ""destroy a       ""skeleton with   ""your sword, try ""using a bomb.@",
        "To open a       ""treasure chest, ""use the pots    ""around it.@",
        "Hop on top of   ""the crystals to ""move forward.@",
        "If you can't go ""over the poles, ""try throwing    ""things you have ""in your hands.@",
        "Jump off the    ""floor above to  ""reach the chest ""on the table.@",
        "To defeat the   ""monsters who    ""hold the key,   ""attack them from""a higher place.@",
        "If the statue   ""looks strange,  ""shoot it with   ""the bow.@",
        "Let's take a    ""picture!        ""    YES  NO<ask>",
        "No picture?! Are""you pullin' my  ""leg?            ""    Yes  No way<ask>",
        "What a bummer!@",
        "Beautiful! I'll ""call this 'Game ""Over.'@",
        "What's your     ""name, young man?""#####? Well     ""here's your     ""album, #####.   ""Give it a look  ""before you      ""leave!@",
        "Let's see if we ""can fill that   ""album!@",
        "11 shots left!  ""What kind of    ""picture should  ""I take?@",
        "10 shots left!  ""What kind of    ""picture should  ""I take?@",
        "9 shots left!   ""What kind of    ""picture should  ""I take?@",
        "8 shots left!   ""What kind of    ""picture should  ""I take?@",
        "7 shots left!   ""What kind of    ""picture should  ""I take?@",
        "6 shots left!   ""What kind of    ""picture should  ""I take?@",
        "5 shots left!   ""What kind of    ""picture should  ""I take?@",
        "4 shots left!   ""What kind of    ""picture should  ""I take?@",
        "3 shots left!   ""What kind of    ""picture should  ""I take?@",
        "2 shots left!   ""What kind of    ""picture should  ""I take?@",
        "1 shots left!   ""What kind of    ""picture should  ""I take?@",
        "Oh no! You're   ""out of film!    ""Don't forget to ""look at your    ""album!@",
        "Hi! I'm the     ""photographer!   ""What a great    ""photo moment!   ""I'll call this  ""'Heads Up!'@",
        "Hey, this       ""represents your ""adventures      ""perfectly!@",
        "I'll call this  ""one 'Close      ""Call.' Hmm.@",
        "I'm too close.@",
        "I should back up"".@",
        "Aaaaaah!@",
        "I'm going back  ""to the store.   ""Bye!@",
        "See me later,   ""when you're     ""alone!@",
        "Are you sure?   ""    YES  NO<ask>",
        "Ah how I love   ""pictures. Hey,  ""#####! What are ""you doing here? @",

        // Credits 4
        "    1998 STAFF    ""    SUPERVISOR    ""     DIRECTOR     ""  SCRIPT WRITER   ""    PROGRAMMER    ""CHARACTER DESIGNER""  SOUND COMPOSER  ""     ART WORK     ""TECHNICAL SUPPORT ""  ENGLISH SCRIPT  ""SPECIAL THANKS TO ",
        "   DEBUG STAFF    ",
        "    1993 STAFF    "" DUNGEON DESIGNER ""   ILLUSTRATOR    ""     PRODUCER     ""EXECUTIVE PRODUCER""                  ",
        "                  ""  TAKASHI TEZUKA  ""YOSINORI TUTIYAMA "" NOBUO MATSUMIYA  ""    EIJI NOTO     ""   KIYOSHI KODA   ""SIGEHIRO KASAMATU ""  MIKIO MISHIMA   ""   KYOKO KIMURA   ""   YUICHI OZAKI   ""   KEIKO IZAWA    ""   N KOGANEZAWA   ""   JIM WORNELL    ""   KEIKO TAMURA   ""    TAMAYO ITO    ""  AKIYA SAKAMOTO  "" R&D2 DEBUG STAFF "" SUPER MARIO CLUB ""YASUHISA YAMAMURA ""  KENSUKE TANABE  "" YOSHIAKI KOIZUMI ""  KAZUAKI MORITA  ""TAKAMITSU KUZUHARA"" MASANAO ARIMOTO  ""  SHIGEFUMI HINO  ""  KAZUMI TOTAKA   ""  MINAKO HAMANO   ""  KOZUE ISHIKAWA  ""  YOUICHI KOTABE  ""    DAN OWSEN     "" TOSHIHIKO NAKAGO ""    KOJI KONDO    "" TOMOAKI KUROUME  "" MASAICHI OKUMURA ""    KANAE WADA    "" SHIGERU MIYAMOTO "" HIROSHI YAMAUCHI ""THE  END          "
        
    };*/
};
}