#pragma once

namespace Zelda
{

enum class RoomName
{
    RM_NONE = -1,
    RM_TAIL_CAVE,
    /*RM_BOTTLE_GROTTO,
    RM_KEY_CAVERN,
    RM_ANGLER_TUNNEL,
    RM_CATFISH_MAW,
    RM_FACE_SHRINE,
    RM_EAGLE_TOWER,
    RM_TURTLE_ROCK,
    RM_WIND_FISH_EGG,
    RM_KANALET_CASTLE,
    RM_COLOUR_DUNGEON,
    RM_DREAM_SHRINE,
    RM_UNDERWORLD,
    RM_OVERWORLD,*/
    RM_COUNT
};

};