#pragma once

#include "Enum.h"

#include <utility>
#include <string>

namespace zelda::core
{
// All locations
enum LocationName
{
    TAIL_CAVE,
    BOTTLE_GROTTO,
    KEY_CAVERN,
    ANGLER_TUNNEL,
    CATFISH_MAW,
    FACE_SHRINE,
    EAGLE_TOWER,
    TURTLE_ROCK,
    WINDFISH_EGG,
    SALE_HOUSE_BANANA,
    POTHOLE_FIELD,
    HOUSE_BY_THE_BAY,
    TRENDY_GAME,
    TOWN_TOOL_SHOP,
    MARIN_AND_TARIN_HOUSE,
    WITCH_HUT,
    YARNA_DESERT,
    UKUKU_PRAIRIE,
    MYSTERIOUS_WOODS,
    MT_TAMARANCH,
    TAL_TAL_MOUNTAIN_RANGE,
    SIGNPOST_MAZE,
    MABE_VILLAGE,
    ANIMAL_VILLAGE,
    CEMETERY,
    RAPIDS_RIDE,
    KOHOLINT_PRAIRIE,
    TORONBO_SHORES,
    MARTHA_BAY,
    EAST_OF_THE_BAY,
    GOPONGA_SWAMP,
    SHRINE,
    KANALET_CASTLE,
    TAL_TAL_HEIGHTS,
    TABAHL_WASTELANDS,
    SOUTH_OF_THE_VILLAGE,
    FISHING_POND,
    MADAM_MEOWMEOW_HOUSE,
    OLD_MAN_ULRIRA_HOUSE,
    WEIRD_MR_WRITE,
    CRAZY_TRACY_HOUSE,
    QUADRUPULETS_HOUSE,
    DREAM_SHRINE,
    TELEPHONE_BOOTH,
    SEASHELL_MANSION,
    RICHARD_VILLA,
    HEN_HOUSE,
    VILLAGE_LIBRARY,
    RAFT_SHOP,
    PHOTO_SHOP
};

// One of 4 location types
enum LocationType
{
    NONE,
    SHOP,
    OWL,
    DUNGEON,
    UNKNOWN
};

struct WorldmapLocation
{
    bool visited;              // Did we visit this location
    LocationType locationType; // Type of the location (see above)
    LocationName locationName; // The name of the location
};

// Worldmap dimensions
constexpr int WORLDMAP_MAX_X = 16;
constexpr int WORLDMAP_MAX_Y = 16;

class Worldmap
{
public:
    Worldmap();

    void setLocation(const int x, const int y);

    void moveMarker(Direction direction);

    bool locationVisited(const int x, const int y) const;

    std::pair<int, int> location() const;

    std::string locationName() const;

    LocationType locationType() const;

private:
    // 16x16 world map

    // TODO: Initially all false (not visited)
    // save file will have 16x16 boolean array with visited or not and we read from there

    WorldmapLocation m_worldmapLocation[WORLDMAP_MAX_X][WORLDMAP_MAX_Y] = {{{false, NONE, TAL_TAL_MOUNTAIN_RANGE},
                                                                            {false, DUNGEON, TURTLE_ROCK},
                                                                            {false, NONE, GOPONGA_SWAMP},
                                                                            {false, UNKNOWN, WEIRD_MR_WRITE},
                                                                            {false, NONE, MYSTERIOUS_WOODS},
                                                                            {false, NONE, MYSTERIOUS_WOODS},
                                                                            {false, NONE, MYSTERIOUS_WOODS},
                                                                            {false, NONE, MYSTERIOUS_WOODS},
                                                                            {false, NONE, MYSTERIOUS_WOODS},
                                                                            {false, NONE, MYSTERIOUS_WOODS},
                                                                            {false, NONE, MABE_VILLAGE},
                                                                            {false, UNKNOWN, VILLAGE_LIBRARY},
                                                                            {false, NONE, SOUTH_OF_THE_VILLAGE},
                                                                            {false, NONE, SOUTH_OF_THE_VILLAGE},
                                                                            {false, NONE, TORONBO_SHORES},
                                                                            {false, NONE, TORONBO_SHORES}},
                                                                           {{false, NONE, TAL_TAL_MOUNTAIN_RANGE},
                                                                            {false, UNKNOWN, TELEPHONE_BOOTH},
                                                                            {false, NONE, GOPONGA_SWAMP},
                                                                            {false, UNKNOWN, TELEPHONE_BOOTH},
                                                                            {false, NONE, MYSTERIOUS_WOODS},
                                                                            {false, NONE, MYSTERIOUS_WOODS},
                                                                            {false, NONE, MYSTERIOUS_WOODS},
                                                                            {false, NONE, MYSTERIOUS_WOODS},
                                                                            {false, SHOP, FISHING_POND},
                                                                            {false, NONE, MYSTERIOUS_WOODS},
                                                                            {false, UNKNOWN, MADAM_MEOWMEOW_HOUSE},
                                                                            {false, UNKNOWN, OLD_MAN_ULRIRA_HOUSE},
                                                                            {false, NONE, SOUTH_OF_THE_VILLAGE},
                                                                            {false, NONE, SOUTH_OF_THE_VILLAGE},
                                                                            {false, NONE, TORONBO_SHORES},
                                                                            {false, NONE, TORONBO_SHORES}},
                                                                           {{false, NONE, TAL_TAL_MOUNTAIN_RANGE},
                                                                            {false, NONE, TAL_TAL_MOUNTAIN_RANGE},
                                                                            {false, NONE, GOPONGA_SWAMP},
                                                                            {false, NONE, GOPONGA_SWAMP},
                                                                            {false, NONE, MYSTERIOUS_WOODS},
                                                                            {false, NONE, MYSTERIOUS_WOODS},
                                                                            {false, NONE, MYSTERIOUS_WOODS},
                                                                            {false, NONE, MYSTERIOUS_WOODS},
                                                                            {false, UNKNOWN, QUADRUPULETS_HOUSE},
                                                                            {false, NONE, MABE_VILLAGE},
                                                                            {false, UNKNOWN, MARIN_AND_TARIN_HOUSE},
                                                                            {false, UNKNOWN, TELEPHONE_BOOTH},
                                                                            {false, NONE, SOUTH_OF_THE_VILLAGE},
                                                                            {false, NONE, SOUTH_OF_THE_VILLAGE},
                                                                            {false, NONE, TORONBO_SHORES},
                                                                            {false, NONE, TORONBO_SHORES}},
                                                                           {{false, NONE, TAL_TAL_MOUNTAIN_RANGE},
                                                                            {false, NONE, TAL_TAL_MOUNTAIN_RANGE},
                                                                            {false, NONE, GOPONGA_SWAMP},
                                                                            {false, NONE, GOPONGA_SWAMP},
                                                                            {false, NONE, MYSTERIOUS_WOODS},
                                                                            {false, NONE, MYSTERIOUS_WOODS},
                                                                            {false, NONE, MYSTERIOUS_WOODS},
                                                                            {false, NONE, MYSTERIOUS_WOODS},
                                                                            {false, UNKNOWN, DREAM_SHRINE},
                                                                            {false, SHOP, TOWN_TOOL_SHOP},
                                                                            {false, NONE, MABE_VILLAGE},
                                                                            {false, SHOP, TRENDY_GAME},
                                                                            {false, NONE, SOUTH_OF_THE_VILLAGE},
                                                                            {false, DUNGEON, TAIL_CAVE},
                                                                            {false, SHOP, SALE_HOUSE_BANANA},
                                                                            {false, NONE, TORONBO_SHORES}},
                                                                           {{false, NONE, TAL_TAL_MOUNTAIN_RANGE},
                                                                            {false, NONE, TAL_TAL_MOUNTAIN_RANGE},
                                                                            {false, DUNGEON, BOTTLE_GROTTO},
                                                                            {false, NONE, GOPONGA_SWAMP},
                                                                            {false, NONE, KOHOLINT_PRAIRIE},
                                                                            {false, NONE, KOHOLINT_PRAIRIE},
                                                                            {false, NONE, KOHOLINT_PRAIRIE},
                                                                            {false, NONE, KOHOLINT_PRAIRIE},
                                                                            {false, NONE, UKUKU_PRAIRIE},
                                                                            {false, NONE, UKUKU_PRAIRIE},
                                                                            {false, UNKNOWN, TELEPHONE_BOOTH},
                                                                            {false, NONE, UKUKU_PRAIRIE},
                                                                            {false, NONE, SIGNPOST_MAZE},
                                                                            {false, NONE, SIGNPOST_MAZE},
                                                                            {false, NONE, TORONBO_SHORES},
                                                                            {false, NONE, TORONBO_SHORES}},
                                                                           {{false, NONE, TAL_TAL_MOUNTAIN_RANGE},
                                                                            {false, NONE, TAL_TAL_MOUNTAIN_RANGE},
                                                                            {false, NONE, TAL_TAL_HEIGHTS},
                                                                            {false, NONE, TAL_TAL_HEIGHTS},
                                                                            {false, SHOP, CRAZY_TRACY_HOUSE},
                                                                            {false, NONE, KOHOLINT_PRAIRIE},
                                                                            {false, SHOP, WITCH_HUT},
                                                                            {false, NONE, KOHOLINT_PRAIRIE},
                                                                            {false, NONE, UKUKU_PRAIRIE},
                                                                            {false, NONE, UKUKU_PRAIRIE},
                                                                            {false, NONE, UKUKU_PRAIRIE},
                                                                            {false, DUNGEON, KEY_CAVERN},
                                                                            {false, NONE, SIGNPOST_MAZE},
                                                                            {false, NONE, SIGNPOST_MAZE},
                                                                            {false, NONE, TORONBO_SHORES},
                                                                            {false, NONE, TORONBO_SHORES}},
                                                                           {{false, UNKNOWN, WINDFISH_EGG},
                                                                            {false, NONE, MT_TAMARANCH},
                                                                            {false, NONE, TAL_TAL_HEIGHTS},
                                                                            {false, NONE, TAL_TAL_HEIGHTS},
                                                                            {false, NONE, TABAHL_WASTELANDS},
                                                                            {false, NONE, TABAHL_WASTELANDS},
                                                                            {false, NONE, CEMETERY},
                                                                            {false, NONE, CEMETERY},
                                                                            {false, NONE, UKUKU_PRAIRIE},
                                                                            {false, NONE, UKUKU_PRAIRIE},
                                                                            {false, NONE, UKUKU_PRAIRIE},
                                                                            {false, NONE, UKUKU_PRAIRIE},
                                                                            {false, NONE, POTHOLE_FIELD},
                                                                            {false, UNKNOWN, RICHARD_VILLA},
                                                                            {false, NONE, MARTHA_BAY},
                                                                            {false, UNKNOWN, HOUSE_BY_THE_BAY}},
                                                                           {{false, NONE, MT_TAMARANCH},
                                                                            {false, NONE, MT_TAMARANCH},
                                                                            {false, NONE, TAL_TAL_HEIGHTS},
                                                                            {false, SHOP, PHOTO_SHOP},
                                                                            {false, NONE, TABAHL_WASTELANDS},
                                                                            {false, NONE, TABAHL_WASTELANDS},
                                                                            {false, NONE, CEMETERY},
                                                                            {false, NONE, CEMETERY},
                                                                            {false, NONE, UKUKU_PRAIRIE},
                                                                            {false, NONE, UKUKU_PRAIRIE},
                                                                            {false, NONE, UKUKU_PRAIRIE},
                                                                            {false, NONE, UKUKU_PRAIRIE},
                                                                            {false, NONE, POTHOLE_FIELD},
                                                                            {false, NONE, POTHOLE_FIELD},
                                                                            {false, NONE, MARTHA_BAY},
                                                                            {false, NONE, MARTHA_BAY}},
                                                                           {{false, NONE, TAL_TAL_MOUNTAIN_RANGE},
                                                                            {false, NONE, TAL_TAL_MOUNTAIN_RANGE},
                                                                            {false, NONE, TAL_TAL_HEIGHTS},
                                                                            {false, NONE, TAL_TAL_HEIGHTS},
                                                                            {false, NONE, KANALET_CASTLE},
                                                                            {false, NONE, KANALET_CASTLE},
                                                                            {false, NONE, KANALET_CASTLE},
                                                                            {false, NONE, KANALET_CASTLE},
                                                                            {false, UNKNOWN, TELEPHONE_BOOTH},
                                                                            {false, NONE, UKUKU_PRAIRIE},
                                                                            {false, NONE, UKUKU_PRAIRIE},
                                                                            {false, NONE, UKUKU_PRAIRIE},
                                                                            {false, NONE, MARTHA_BAY},
                                                                            {false, NONE, MARTHA_BAY},
                                                                            {false, UNKNOWN, TELEPHONE_BOOTH},
                                                                            {false, NONE, MARTHA_BAY}},
                                                                           {{false, NONE, TAL_TAL_MOUNTAIN_RANGE},
                                                                            {false, NONE, TAL_TAL_MOUNTAIN_RANGE},
                                                                            {false, NONE, TAL_TAL_HEIGHTS},
                                                                            {false, NONE, TAL_TAL_HEIGHTS},
                                                                            {false, NONE, KANALET_CASTLE},
                                                                            {false, NONE, KANALET_CASTLE},
                                                                            {false, NONE, KANALET_CASTLE},
                                                                            {false, NONE, KANALET_CASTLE},
                                                                            {false, NONE, UKUKU_PRAIRIE},
                                                                            {false, NONE, UKUKU_PRAIRIE},
                                                                            {false, NONE, UKUKU_PRAIRIE},
                                                                            {false, NONE, UKUKU_PRAIRIE},
                                                                            {false, NONE, MARTHA_BAY},
                                                                            {false, DUNGEON, CATFISH_MAW},
                                                                            {false, NONE, MARTHA_BAY},
                                                                            {false, NONE, MARTHA_BAY}},
                                                                           {{false, SHOP, HEN_HOUSE},
                                                                            {false, NONE, TAL_TAL_MOUNTAIN_RANGE},
                                                                            {false, NONE, TAL_TAL_HEIGHTS},
                                                                            {false, NONE, TAL_TAL_HEIGHTS},
                                                                            {false, NONE, KANALET_CASTLE},
                                                                            {false, NONE, KANALET_CASTLE},
                                                                            {false, NONE, KANALET_CASTLE},
                                                                            {false, NONE, KANALET_CASTLE},
                                                                            {false, UNKNOWN, SEASHELL_MANSION},
                                                                            {false, NONE, UKUKU_PRAIRIE},
                                                                            {false, NONE, UKUKU_PRAIRIE},
                                                                            {false, NONE, UKUKU_PRAIRIE},
                                                                            {false, NONE, MARTHA_BAY},
                                                                            {false, NONE, MARTHA_BAY},
                                                                            {false, NONE, MARTHA_BAY},
                                                                            {false, NONE, MARTHA_BAY}},
                                                                           {{false, NONE, TAL_TAL_MOUNTAIN_RANGE},
                                                                            {false, NONE, TAL_TAL_MOUNTAIN_RANGE},
                                                                            {false, DUNGEON, ANGLER_TUNNEL},
                                                                            {false, NONE, TAL_TAL_HEIGHTS},
                                                                            {false, UNKNOWN, TELEPHONE_BOOTH},
                                                                            {false, NONE, KANALET_CASTLE},
                                                                            {false, NONE, KANALET_CASTLE},
                                                                            {false, NONE, KANALET_CASTLE},
                                                                            {false, NONE, UKUKU_PRAIRIE},
                                                                            {false, NONE, UKUKU_PRAIRIE},
                                                                            {false, NONE, UKUKU_PRAIRIE},
                                                                            {false, NONE, UKUKU_PRAIRIE},
                                                                            {false, NONE, MARTHA_BAY},
                                                                            {false, UNKNOWN, TELEPHONE_BOOTH},
                                                                            {false, NONE, MARTHA_BAY},
                                                                            {false, NONE, MARTHA_BAY}},
                                                                           {{false, NONE, TAL_TAL_MOUNTAIN_RANGE},
                                                                            {false, NONE, TAL_TAL_MOUNTAIN_RANGE},
                                                                            {false, NONE, TAL_TAL_HEIGHTS},
                                                                            {false, NONE, TAL_TAL_HEIGHTS},
                                                                            {false, NONE, RAPIDS_RIDE},
                                                                            {false, NONE, RAPIDS_RIDE},
                                                                            {false, NONE, RAPIDS_RIDE},
                                                                            {false, NONE, RAPIDS_RIDE},
                                                                            {false, DUNGEON, FACE_SHRINE},
                                                                            {false, NONE, SHRINE},
                                                                            {false, NONE, SHRINE},
                                                                            {false, NONE, SHRINE},
                                                                            {false, NONE, ANIMAL_VILLAGE},
                                                                            {false, NONE, ANIMAL_VILLAGE},
                                                                            {false, NONE, EAST_OF_THE_BAY},
                                                                            {false, NONE, EAST_OF_THE_BAY}},
                                                                           {{false, NONE, TAL_TAL_MOUNTAIN_RANGE},
                                                                            {false, NONE, TAL_TAL_MOUNTAIN_RANGE},
                                                                            {false, NONE, TAL_TAL_HEIGHTS},
                                                                            {false, NONE, TAL_TAL_HEIGHTS},
                                                                            {false, NONE, RAPIDS_RIDE},
                                                                            {false, NONE, RAPIDS_RIDE},
                                                                            {false, NONE, RAPIDS_RIDE},
                                                                            {false, NONE, RAPIDS_RIDE},
                                                                            {false, NONE, SHRINE},
                                                                            {false, NONE, SHRINE},
                                                                            {false, NONE, SHRINE},
                                                                            {false, NONE, SHRINE},
                                                                            {false, NONE, ANIMAL_VILLAGE},
                                                                            {false, NONE, ANIMAL_VILLAGE},
                                                                            {false, NONE, EAST_OF_THE_BAY},
                                                                            {false, NONE, EAST_OF_THE_BAY}},
                                                                           {{false, DUNGEON, EAGLE_TOWER},
                                                                            {false, NONE, TAL_TAL_MOUNTAIN_RANGE},
                                                                            {false, NONE, TAL_TAL_HEIGHTS},
                                                                            {false, NONE, TAL_TAL_HEIGHTS},
                                                                            {false, NONE, RAPIDS_RIDE},
                                                                            {false, NONE, RAPIDS_RIDE},
                                                                            {false, NONE, RAPIDS_RIDE},
                                                                            {false, NONE, RAPIDS_RIDE},
                                                                            {false, NONE, RAPIDS_RIDE},
                                                                            {false, NONE, RAPIDS_RIDE},
                                                                            {false, NONE, SHRINE},
                                                                            {false, NONE, SHRINE},
                                                                            {false, NONE, YARNA_DESERT},
                                                                            {false, NONE, YARNA_DESERT},
                                                                            {false, NONE, YARNA_DESERT},
                                                                            {false, NONE, YARNA_DESERT}},
                                                                           {{false, NONE, TAL_TAL_MOUNTAIN_RANGE},
                                                                            {false, NONE, TAL_TAL_MOUNTAIN_RANGE},
                                                                            {false, NONE, TAL_TAL_HEIGHTS},
                                                                            {false, SHOP, RAFT_SHOP},
                                                                            {false, NONE, RAPIDS_RIDE},
                                                                            {false, NONE, RAPIDS_RIDE},
                                                                            {false, NONE, RAPIDS_RIDE},
                                                                            {false, NONE, RAPIDS_RIDE},
                                                                            {false, NONE, RAPIDS_RIDE},
                                                                            {false, NONE, RAPIDS_RIDE},
                                                                            {false, NONE, SHRINE},
                                                                            {false, NONE, SHRINE},
                                                                            {false, NONE, YARNA_DESERT},
                                                                            {false, NONE, YARNA_DESERT},
                                                                            {false, NONE, YARNA_DESERT},
                                                                            {false, NONE, YARNA_DESERT}}};

    // Position of Link in the worldmap
    int m_worldX;
    int m_worldY;
};

} // namespace zelda::core