#ifndef INPUT_CONTROL_H
#define INPUT_CONTROL_H 

// Keyword control for Gameboy controls
// Adjust here

// Returns true if any of the gamepad keys are pressed
#define IS_GAMEPAD_PRESSED(KEYBOARD_STATE) (KEYBOARD_STATE[BUTTON_A] || \
KEYBOARD_STATE[BUTTON_B] || \
KEYBOARD_STATE[BUTTON_UP] || \
KEYBOARD_STATE[BUTTON_DOWN] || \
KEYBOARD_STATE[BUTTON_LEFT] || \
KEYBOARD_STATE[BUTTON_RIGHT] || \
KEYBOARD_STATE[BUTTON_START] || \
KEYBOARD_STATE[BUTTON_SELECT])

#define BUTTON_A SDL_SCANCODE_Z
#define BUTTON_B SDL_SCANCODE_X
#define BUTTON_UP SDL_SCANCODE_UP
#define BUTTON_DOWN SDL_SCANCODE_DOWN
#define BUTTON_LEFT SDL_SCANCODE_LEFT
#define BUTTON_RIGHT SDL_SCANCODE_RIGHT
#define BUTTON_START SDL_SCANCODE_RETURN
#define BUTTON_SELECT SDL_SCANCODE_J


#endif 